import {recommendedAI,RECOMMENDED_MODELS} from './lib/recommended-ai';
import {useEffect,useState} from 'react';
import {KeyRound,Save,Trash2,RefreshCw,Loader2,Network} from 'lucide-react';
import {api,native} from './lib/desktop';
import {apiProviderIds,providerIds,providerNames,isFreeSlug,validateAIConfig,defaultAIConfig,type APIProviderId,type ProviderId,type AIConfig,type KeyStatus,type ChatGPTInfo,type ModelChoice} from './lib/ai-settings';
import {isCodingEmployee} from './lib/ai-policy';
import type {Employee} from './lib/workspace';
import {toast} from 'sonner';
type Props={config:AIConfig;keys:KeyStatus;chatgpt:ChatGPTInfo;employees:Employee[];locked:boolean;refresh:()=>Promise<unknown>};
export default function APISettings({config,keys,chatgpt,employees,locked,refresh}:Props){
 const [draft,setDraft]=useState(config),[dirty,setDirty]=useState(false),[tab,setTab]=useState<APIProviderId>('openrouter'),[key,setKey]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[manual,setManual]=useState<Record<string,boolean>>({});
 useEffect(()=>{if(!dirty)setDraft(config);},[config,dirty]);
 const disabled=locked||!!busy,settings=draft.providers[tab];
 function update(fn:(next:AIConfig)=>void){setDraft(previous=>{const next=structuredClone(previous);fn(next);return next;});setDirty(true);setError('');}
 async function action(name:string,fn:()=>Promise<unknown>){if(disabled)return;setBusy(name);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function saveConfig(next=draft){const clean=validateAIConfig(next,new Set(employees.map(e=>e.id)));await api('/api/ai-settings',{config:clean});await refresh();setDraft(clean);setDirty(false);toast.success('Model dan penyedia karyawan disimpan.');}
 async function saveKey(){await native('apiSaveKey',JSON.stringify({provider:tab,key:key.trim()}));setKey('');await refresh();toast.success('API key disimpan terenkripsi.');}
 async function removeKey(){await native('apiRemoveKey',JSON.stringify({provider:tab}));await refresh();toast.success('API key dihapus.');}
 async function loadModels(){const models:ModelChoice[]=await native('apiModels',JSON.stringify({provider:tab,baseUrl:settings.baseUrl}),180000);update(next=>{const p=next.providers[tab];p.models=models.slice(0,2000);const available=tab==='openrouter'&&p.freeOnly?p.models.filter(m=>isFreeSlug(m.id)):p.models;if(!p.general)p.general=available[0]?.id||'';if(!p.coding)p.coding=p.general;});toast.success('Daftar model dimuat. Simpan pilihan model untuk menerapkannya.');}
 async function changeDefault(value:ProviderId){if(dirty)await saveConfig();await native('apiDefault',value);await refresh();}
 function modelsFor(provider:ProviderId){if(provider==='chatgpt')return chatgpt.models.map(m=>({id:m.slug,name:m.display_name}));const p=draft.providers[provider];return provider==='openrouter'&&p.freeOnly?p.models.filter(m=>isFreeSlug(m.id)):p.models;}
 function picker(value:string,models:ModelChoice[],onChange:(value:string)=>void,label:string,id:string,inherit=false){
  const known=models.some(m=>m.id===value),showManual=!inherit&&(manual[id]||!!value&&!known),selectValue=showManual?'__manual__':value;
  return <div className="model-picker"><label htmlFor={id}>{label}</label><select id={id} className="local-key-input" disabled={disabled||inherit} value={inherit?'':selectValue} onChange={e=>{if(e.target.value==='__manual__'){setManual(v=>({...v,[id]:true}));if(known)onChange('');}else{setManual(v=>({...v,[id]:false}));onChange(e.target.value);}}}><option value="">{inherit?'Mengikuti model default':'Pilih model'}</option>{models.map(m=><option key={m.id} value={m.id}>{m.name} · {m.id}</option>)}{!inherit&&<option value="__manual__">Masukkan ID model manual…</option>}</select>{showManual&&<input className="local-key-input" aria-label={'ID model '+label} value={value} maxLength={256} disabled={disabled} placeholder="ID model dari dokumentasi penyedia" onChange={e=>onChange(e.target.value.trim())}/>}</div>;
 }
 function freeOnly(value:boolean){update(next=>{const p=next.providers.openrouter;p.freeOnly=value;if(value){const defaults=defaultAIConfig().providers.openrouter;if(!isFreeSlug(p.general))p.general=defaults.general;if(!isFreeSlug(p.coding))p.coding=defaults.coding;for(const r of Object.values(next.employees))if(r.provider==='openrouter'&&!isFreeSlug(r.model))r.model='';}});}
 return <>
 <section className="settings-card api-settings"><div className="settings-heading"><span className="agent-icon"><Network size={24}/></span><div><h2>Penyedia & API key</h2><p>Satu kantor · AI berbeda untuk setiap karyawan</p></div></div>
 <label className="local-key-label" htmlFor="default-ai-provider">Penyedia default kantor</label><select id="default-ai-provider" className="local-key-input" value={keys.provider} disabled={disabled} onChange={e=>void action('default',()=>changeDefault(e.target.value as ProviderId))}>{providerIds.map(id=><option key={id} value={id}>{providerNames[id]}</option>)}</select><p className="local-help">Karyawan yang memilih Default mengikuti penyedia dan model umum/coding di sini. Pilihan khusus karyawan tetap berlaku.</p>
 <div className="api-provider-tabs" role="group" aria-label="Pilih penyedia API">{apiProviderIds.map(id=><button key={id} className={tab===id?'active':''} disabled={disabled} onClick={()=>{setTab(id);setKey('');setError('');}}>{providerNames[id]}<span className={keys.keys[id]?'dot connected':'dot'}/></button>)}</div>
 {error&&<p className="chatgpt-error" role="alert">{error}</p>}
 <div className="api-provider-panel"><div className="api-provider-title"><h3>{providerNames[tab]}</h3><span className="settings-status">{keys.keys[tab]?'Key tersimpan':'Belum ada key'}</span></div>
 {tab==='custom'&&<label className="local-key-label" htmlFor="custom-api-url">Base URL HTTPS<input id="custom-api-url" className="local-key-input" value={settings.baseUrl} disabled={disabled} maxLength={2048} placeholder="https://api.example.com/v1" onChange={e=>update(next=>{next.providers.custom.baseUrl=e.target.value.trim();next.providers.custom.models=[];})}/><span className="local-help">URL dasar API, tanpa /chat/completions. Key dan konteks pekerjaan dikirim ke alamat ini.</span></label>}
 <label className="local-key-label" htmlFor="provider-api-key">API key {keys.keys[tab]?'(isi untuk mengganti)':''}</label><input id="provider-api-key" className="local-key-input" type="password" value={key} disabled={disabled} maxLength={4096} autoComplete="off" spellCheck={false} placeholder={'API key '+providerNames[tab]} onChange={e=>setKey(e.target.value)}/>
 <div className="local-actions"><button className="primary" disabled={disabled||!key.trim()} onClick={()=>void action('key',saveKey)}>{busy==='key'?<Loader2 size={16} className="spin"/>:<KeyRound size={16}/>} Simpan key</button>{keys.keys[tab]&&<button className="outline" disabled={disabled} onClick={()=>void action('remove',removeKey)}><Trash2 size={16}/> Hapus key</button>}<button className="outline" disabled={disabled||!keys.keys[tab]} onClick={()=>void action('models',loadModels)}>{busy==='models'?<Loader2 size={16} className="spin"/>:<RefreshCw size={16}/>} Muat model</button></div>
 {tab==='openrouter'&&<label className="api-free-toggle"><input type="checkbox" checked={settings.freeOnly} disabled={disabled} onChange={e=>freeOnly(e.target.checked)}/> Hanya model gratis (batas harga nol)</label>}
 <div className="chatgpt-models">{picker(settings.general,modelsFor(tab),model=>update(next=>{next.providers[tab].general=model;}),'Model umum','api-general-model-'+tab)}{picker(settings.coding,modelsFor(tab),model=>update(next=>{next.providers[tab].coding=model;}),'Model coding','api-coding-model-'+tab)}</div>
 <label className="local-key-label" htmlFor="api-token-limit">Batas token jawaban<input id="api-token-limit" className="local-key-input" type="number" min={512} max={32768} value={settings.maxTokens} disabled={disabled} onChange={e=>update(next=>{next.providers[tab].maxTokens=Number(e.target.value);})}/></label>
 <p className="local-help">Muat daftar dari penyedia atau isi ID model manual. Biaya dan kuota mengikuti akun penyedia. OpenAI API ditagih terpisah dari paket ChatGPT. Key tidak ikut backup.</p></div>
 </section>
 <section className="settings-card api-settings"><div className="settings-heading"><span className="agent-icon"><Network size={24}/></span><div><h2>AI untuk setiap karyawan</h2><p>Amii membagi tugas; setiap spesialis menggunakan pilihan AI-nya.</p></div></div>
 <div className="recommended-preset"><div><strong>Tim gratis yang direkomendasikan</strong><p>Gemma untuk Amii, Nara, Kira, Luna, Mika, Achi, Lora & Dante. North Mini Code untuk Rei & Sora. Batas jawaban minimal 8192 token.</p></div><button className="outline" disabled={disabled||!keys.keys.openrouter} onClick={()=>void action('preset',()=>saveConfig(recommendedAI(draft)))}><Network size={16}/> Terapkan preset gratis</button><small>Preset disimpan langsung untuk sepuluh karyawan bawaan. Model karyawan tambahan tetap sesuai pilihanmu. Kuota dan ketersediaan mengikuti OpenRouter.</small></div>
 <details className="recommended-guide"><summary>Alternatif model & instruksi kerja karyawan</summary><ul>{RECOMMENDED_MODELS.map(m=><li key={m.id}><strong>{m.name}</strong><code>{m.id}</code></li>)}</ul><p>Daftar ini adalah rekomendasi, bukan hasil tes koneksi. Gunakan Muat model untuk melihat katalog terbaru; jika model hilang, pilih alternatif yang tersedia.</p>{employees.map(e=><details key={e.id}><summary>{e.name} · {e.role}</summary><p>{e.instruction}</p></details>)}</details>
 <div className="employee-model-table"><table><thead><tr><th>Karyawan</th><th>Penyedia</th><th>Model</th></tr></thead><tbody>{employees.map(employee=>{const r=draft.employees[employee.id]||{provider:'default' as const,model:''},effective=r.provider==='default'?keys.provider:r.provider;return <tr key={employee.id}><td><strong>{employee.name}</strong><small>{employee.role}</small></td><td><select className="local-key-input" aria-label={'Penyedia '+employee.name} disabled={disabled} value={r.provider} onChange={e=>{setManual(v=>({...v,['employee-model-'+employee.id]:false}));update(next=>{next.employees[employee.id]={provider:e.target.value as typeof r.provider,model:''};});}}><option value="default">Default kantor</option>{providerIds.map(id=><option key={id} value={id}>{providerNames[id]}</option>)}</select><small>{effective==='chatgpt'?(chatgpt.connected&&chatgpt.permitted?'Login tersedia':'Login belum tersedia'):(keys.keys[effective]?'Key tersimpan':'Key belum tersimpan')}</small></td><td>{picker(r.model,modelsFor(effective),model=>update(next=>{next.employees[employee.id]={provider:r.provider,model};}),employee.name,'employee-model-'+employee.id,r.provider==='default')}<small>{!r.model&&(effective==='chatgpt'?(isCodingEmployee(employee)?chatgpt.coding:chatgpt.general):(isCodingEmployee(employee)?draft.providers[effective].coding:draft.providers[effective].general))||r.model||'Belum memilih model'}</small></td></tr>;})}</tbody></table></div>
 <p className="local-help">Mika dapat memakai Gemini, Luna memakai ChatGPT dan Sora memakai Groq dalam proyek yang sama. Maksimal tiga permintaan bersamaan; hasil tetap diteruskan lewat papan tugas.</p>
 {locked&&<p className="local-help">Tunggu tugas tim selesai sebelum mengubah koneksi.</p>}{error&&<p className="chatgpt-error" role="alert">{error}</p>}<div className="local-actions"><button className="primary" disabled={disabled||!dirty} onClick={()=>void action('save',()=>saveConfig())}>{busy==='save'?<Loader2 size={16} className="spin"/>:<Save size={16}/>} Simpan model & karyawan</button>{dirty&&<span className="local-help">Ada perubahan belum disimpan.</span>}</div>
 </section></>;
}
