import {useRef,useState} from 'react';
import UpdateSettings from './UpdateSettings';
import {Sparkles,Lock,Save,Download,Upload,Trash2,Loader2} from 'lucide-react';
import {native,exportBackup,importBackup} from './lib/desktop';
import {toast} from 'sonner';
export default function LocalSettings({connected,model,codingModel,refresh}:{connected:boolean;model:string;codingModel:string;refresh:()=>Promise<unknown>}){
 const [key,setKey]=useState(''),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 async function saveKey(){setBusy(true);try{await native('saveKey',key.trim());setKey('');await refresh();toast.success('API key disimpan terenkripsi di PC ini.');}catch(error){toast.error((error as Error).message);}finally{setBusy(false);}}
 async function removeKey(){setBusy(true);try{await native('removeKey');setKey('');await refresh();toast.success('API key dihapus dari PC.');}catch(error){toast.error((error as Error).message);}finally{setBusy(false);}}
 async function backup(){try{const text=await exportBackup(),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='DITASHA-Backup-'+new Date().toISOString().slice(0,10)+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(error){toast.error((error as Error).message);}}
 async function restore(file:File|undefined){if(!file)return;if(!window.confirm('Import backup ini akan mengganti proyek, karyawan, dan chat lokal. Export backup saat ini terlebih dahulu bila ingin menyimpannya. Lanjutkan?'))return;setBusy(true);try{await importBackup(await file.text());await refresh();toast.success('Backup berhasil diimpor.');}catch(error){toast.error((error as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
 return <div className="page settings-page"><p className="eyebrow teal">DITASHA · DI PC KAMU</p><h1>Pengaturan</h1><p className="lead">Kantor dan data lokal. Internet untuk jawaban AI dan update aplikasi.</p>
 <section className="settings-card"><div className="settings-heading"><span className="agent-icon"><Sparkles size={24}/></span><div><h2>Koneksi OpenRouter</h2><p>Model gratis · langsung dari PC</p></div><span className="settings-status">{connected?'Key tersimpan':'Belum terhubung'}</span></div>
 <p>Masukkan API key OpenRouter kamu. Key disimpan terenkripsi oleh Windows untuk akun pengguna ini.</p>
 <label htmlFor="local-api-key" className="local-key-label">API key {connected?'(isi untuk mengganti)':''}</label><input id="local-api-key" type="password" autoComplete="off" spellCheck={false} value={key} maxLength={256} onChange={e=>setKey(e.target.value)} placeholder="sk-or-v1-…" className="local-key-input"/>
 <div className="local-actions"><button className="primary" disabled={busy||!key.trim()} onClick={()=>void saveKey()}>{busy?<Loader2 size={16} className="spin"/>:<Save size={16}/>} Simpan key</button>{connected&&<button className="outline" disabled={busy} onClick={()=>void removeKey()}><Trash2 size={16}/> Hapus key</button>}</div>
 <p className="local-help">Status menunjukkan key tersimpan. Validitas key diperiksa saat mengirim pesan.</p>
 <div className="free-model-config"><p><span>Umum</span><code>{model}</code></p><p><span>Coding</span><code>{codingModel}</code></p></div><p className="free-model-note">Hanya model gratis, termasuk fallback gratis. Kuota dan ketersediaan mengikuti OpenRouter.</p></section>
 <div className="security-note"><Lock size={22}/><div><h3>Workspace berjalan di PC.</h3><p>Proyek, catatan, karyawan, dan chat tersimpan di PC ini. Saat meminta jawaban, pesan dan konteks proyek dikirim ke OpenRouter. Tidak ada login ChatGPT atau koneksi ke website workspace.</p></div></div>
 <UpdateSettings/><section className="settings-card"><h2>Backup lokal</h2><p>Export data sebelum pindah PC atau mengimpor backup. API key tidak ikut di dalam backup.</p><div className="local-actions"><button className="outline" disabled={busy} onClick={()=>void backup()}><Download size={16}/> Export backup</button><button className="outline" disabled={busy} onClick={()=>input.current?.click()}><Upload size={16}/> Import backup</button><input ref={input} type="file" accept=".json,application/json" hidden onChange={e=>void restore(e.target.files?.[0])}/></div></section>
 <section className="settings-card"><h2>DITASHA Workspace Local</h2><dl><div><dt>Versi</dt><dd>Windows x64 · versi di panel update</dd></div><div><dt>Penyimpanan</dt><dd>PC ini · folder LocalAppData DITASHA</dd></div><div><dt>AI</dt><dd>OpenRouter · mode gratis</dd></div></dl></section></div>;
}
