import {Fragment,type ReactNode} from 'react';
import {Download,FileText} from 'lucide-react';
import {native} from './lib/desktop';
import {generatedFiles,safeFilename} from './lib/chat-files';
import {toast} from 'sonner';
export async function saveResult(name:string,content:string){try{const r=await native('saveResult',JSON.stringify({name:safeFilename(name),content}));if(r?.saved)toast.success('File berhasil disimpan');}catch(e){toast.error((e as Error).message);}}
function inline(text:string):ReactNode[]{return text.split(/(\*\*[^*]+\*\*|`[^`]+`|\[[^\]]+\]\(https?:\/\/[^\s)]+\))/g).map((s,i)=>{if(s.startsWith('**')&&s.endsWith('**'))return <strong key={i}>{s.slice(2,-2)}</strong>;if(s.startsWith('`')&&s.endsWith('`'))return <code key={i}>{s.slice(1,-1)}</code>;const link=s.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);if(link)return <a key={i} href={link[2]} onClick={e=>{e.preventDefault();void native('openLink',link[2]).catch(e=>toast.error(e.message));}}>{link[1]}</a>;return <Fragment key={i}>{s}</Fragment>;});}
export default function MessageBody({text}:{text:string}){
 const lines=text.replace(/\r\n?/g,'\n').split('\n'),blocks:ReactNode[]=[],files=generatedFiles(text);let fileIndex=0;
 for(let i=0;i<lines.length;){const line=lines[i];if(!line.trim()){i++;continue;}if(line.startsWith('```')){const info=line.slice(3).trim();const code:string[]=[];i++;while(i<lines.length&&!lines[i].startsWith('```'))code.push(lines[i++]);const complete=i<lines.length;i+=complete?1:0;const file=complete?files[fileIndex++]:undefined;blocks.push(<div className="code-card" key={i}><div className="code-caption"><span>{file?.name||info||'Kode'}</span>{file&&<button onClick={()=>void saveResult(file.name,file.content)}><Download size={14}/> Simpan file</button>}</div><pre><code>{code.join('\n')}</code></pre></div>);continue;}
 const heading=line.match(/^(#{1,6})\s+(.*)/);if(heading){blocks.push(<h3 className={'md-heading md-h'+heading[1].length} key={i}>{inline(heading[2])}</h3>);i++;continue;}if(/^\s*(---+|\*\*\*+)\s*$/.test(line)){blocks.push(<hr key={i++}/>);continue;}
 if(line.includes('|')&&/^\s*\|?\s*:?-{3}/.test(lines[i+1]||'')){const cells=(s:string)=>s.trim().replace(/^\||\|$/g,'').split('|').map(x=>x.trim());const head=cells(line);i+=2;const rows:string[][]=[];while(i<lines.length&&lines[i].includes('|'))rows.push(cells(lines[i++]));blocks.push(<div className="md-table" key={i}><table><thead><tr>{head.map((s,k)=><th key={k}>{inline(s)}</th>)}</tr></thead><tbody>{rows.map((r,k)=><tr key={k}>{r.map((s,j)=><td key={j}>{inline(s)}</td>)}</tr>)}</tbody></table></div>);continue;}
 const list=line.match(/^\s*(\d+\.|[-*])\s+(.*)/);if(list){const ordered=/\d/.test(list[1]);const items:ReactNode[]=[];let start=ordered?parseInt(list[1]):1;while(i<lines.length){const m=lines[i].match(ordered?/^\s*\d+\.\s+(.*)/:/^\s*[-*]\s+(.*)/);if(!m)break;items.push(<li key={i++}>{inline(m[1])}</li>);}blocks.push(ordered?<ol start={start} key={i}>{items}</ol>:<ul key={i}>{items}</ul>);continue;}
 if(line.startsWith('> ')){blocks.push(<blockquote key={i}>{inline(line.slice(2))}</blockquote>);i++;continue;}
 const paragraph=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6}\s|```|>|\s*[-*]\s|\s*\d+\.\s)/.test(lines[i]))paragraph.push(lines[i++]);blocks.push(<p key={i}>{inline(paragraph.join('\n'))}</p>);
 }
 return <div className="markdown-body">{blocks}{files.length>0&&<div className="deliverables"><div><FileText size={17}/><strong>File dari tim AI</strong><small>Simpan, lalu tinjau sebelum digunakan.</small></div>{files.map((f,i)=><button key={i} onClick={()=>void saveResult(f.name,f.content)}><FileText size={16}/><span>{f.name}<small>{f.content.length.toLocaleString('id-ID')} karakter</small></span><Download size={16}/></button>)}</div>}</div>;
}
