import {useEffect,useState} from 'react';
import {syncNative,type SyncInfo} from './lib/cloud-sync';
import {native} from './lib/desktop';
import {toast} from 'sonner';
export default function SyncSettings({locked}:{locked:boolean}){
 const [url,setUrl]=useState('https://workspace.gremoryy.my.id'),[code,setCode]=useState(''),[name,setName]=useState('PC Foxu'),[info,setInfo]=useState<SyncInfo>({paired:false}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{syncNative('syncStatus').then(r=>{setInfo(r);if(r.url)setUrl(r.url)}).catch(e=>setError(e.message))},[]);
 const changed=()=>window.dispatchEvent(new Event('ditasha-sync-changed'));
 async function pair(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const address=new URL(url);if(address.protocol!=='https:'||address.username||address.password||address.search||address.hash||address.pathname!=='/')throw new Error('Gunakan alamat HTTPS server saja, tanpa path atau password.');await syncNative('syncPair',{url:address.origin,code:code.replaceAll(' ',''),name});setInfo(await syncNative('syncStatus'));setCode('');changed();toast.success('PC dipasangkan. Sync pertama sedang berjalan.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="settings-card sync-settings"><h2>Sync ponsel · Android & web</h2><p>Hubungkan PC ke server Debian milikmu. Percakapan terbaru, proyek, nama/model karyawan, ledger, metadata email pembayaran, dan Excel Lora/Achi disalin ke server. API key, password Gmail, sesi ChatGPT, dan akses folder tetap di PC.</p>{error&&<p className="tool-error" role="alert">{error}</p>}{info.paired?<><p className="sync-connected">PC terhubung ke {info.url}</p><div className="tool-actions"><button className="outline" disabled={busy||locked} onClick={()=>void native('openLink',info.url||url).catch(e=>toast.error(e.message))}>Buka aplikasi ponsel</button><button className="outline" disabled={busy||locked} onClick={()=>{if(window.confirm('Hentikan sync PC ini? Untuk mencabut token di server, gunakan Lepas PC pada aplikasi ponsel.')){setBusy(true);syncNative('syncDisconnect').then(r=>{setInfo(r);changed()}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}}>Hentikan sync lokal</button></div></>:<form className="tool-form" onSubmit={e=>void pair(e)}><label className="wide">Alamat server<input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://workspace.gremoryy.my.id"/></label><label>Kode dari ponsel<input required inputMode="numeric" pattern="[0-9]{8}" maxLength={8} value={code} onChange={e=>setCode(e.target.value)} placeholder="8 digit"/></label><label>Nama PC<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={busy||locked}>Pasangkan & mulai sync</button></form>}<ol className="sync-steps"><li>Pasang server, arahkan DNS, dan login pada aplikasi Android / website.</li><li>Buka Perangkat → Buat kode pairing, lalu masukkan kode pada PC ini.</li><li>Biarkan aplikasi PC terbuka untuk menjalankan tugas dan mengirim hasil. Saat PC offline, tugas ponsel tetap antre.</li></ol><p className="tool-note">Satu PC aktif per akun. Pairing PC baru mencabut akses PC sebelumnya. Hasil terakhir tetap terlihat saat PC offline. Tampilan cloud menyimpan percakapan terbaru dan ledger terbaru; backup lengkap tetap melalui PC.</p></section>;
}
