import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {dirname,join} from 'node:path';
import {randomUUID,randomInt} from 'node:crypto';
import {openStore,token,hash,verifyPassword} from './store.mjs';
const root=dirname(fileURLToPath(import.meta.url));
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const check=(test,message='Permintaan tidak valid.',status=400)=>{if(!test){const e=new Error(message);e.status=status;throw e;}};
const str=(value,max)=>typeof value==='string'&&value.length<=max;
const identifier=value=>str(value,100)&&/^[a-zA-Z0-9_-]+$/.test(value);
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
function cleanSnapshot(value){
 check(value&&Array.isArray(value.chats)&&Array.isArray(value.messages)&&Array.isArray(value.projects)&&Array.isArray(value.employees));
 check(value.chats.length<=1000&&value.messages.length<=500&&value.projects.length<=300&&value.employees.length<=100);
 const employees=value.employees.map(e=>{check(identifier(e.id)&&str(e.name,60)&&str(e.role,100));return {id:e.id,name:e.name,role:e.role,color:str(e.color,20)?e.color:'#50d6ba',model:str(e.model,180)?e.model:'',provider:str(e.provider,30)?e.provider:''};});
 const projects=value.projects.map(p=>{check(identifier(p.id)&&str(p.name,100)&&str(p.description,1000));return {id:p.id,name:p.name,description:p.description};});
 const chats=value.chats.map(c=>{check(identifier(c.id)&&str(c.title,100)&&identifier(c.agent));return {id:c.id,title:c.title,agent:c.agent,project_id:identifier(c.project_id)?c.project_id:null,updated:Number(c.updated)||0};});
 const ids=new Set(chats.map(c=>c.id));
 const messages=value.messages.map(m=>{check(identifier(m.id)&&ids.has(m.chat_id)&&['user','assistant'].includes(m.role)&&str(m.content,1000000));return {id:m.id,chat_id:m.chat_id,role:m.role,content:m.content,created:Number(m.created)||0};});
 let money=null;if(value.money){const m=value.money;check(Array.isArray(m.transactions)&&m.transactions.length<=10000);money={transactions:m.transactions.map(t=>{check(identifier(t.id)&&str(t.date,10)&&['income','expense'].includes(t.kind)&&Number.isSafeInteger(t.amount)&&t.amount>0&&t.amount<=1e12&&str(t.category,80)&&str(t.note,500));return {id:t.id,date:t.date,kind:t.kind,amount:t.amount,category:t.category,note:t.note};}),budgets:{}};}
 let mail=null;if(value.mail){const m=value.mail;check(Array.isArray(m.payments)&&m.payments.length<=200&&Number.isInteger(m.total)&&m.total>=0);mail={lastRun:str(m.lastRun,50)?m.lastRun:'',total:m.total,pending:Number(m.pending)||0,payments:m.payments.map(p=>{check(identifier(p.id)&&str(p.subject,500)&&str(p.account,254)&&str(p.review,30)&&str(p.paymentType,80)&&str(p.currency,3)&&(p.amount===null||Number.isFinite(p.amount)));return {id:p.id,subject:p.subject,account:p.account,review:p.review,paymentType:p.paymentType,amount:p.amount,currency:p.currency,date:str(p.date,120)?p.date:'',dueDate:str(p.dueDate,20)?p.dueDate:''};})};}
 let report=null;if(value.report){check(str(value.report.base64,5600000)&&/^[A-Za-z0-9+/]*={0,2}$/.test(value.report.base64));const bytes=Buffer.from(value.report.base64,'base64');check(bytes.length<=4000000&&bytes[0]===0x50&&bytes[1]===0x4b);report={base64:value.report.base64};}
 return {employees,projects,chats,messages,money,mail,report,partial:!!value.partial};
}
function taskRequest(body){
 check(body&&UUID.test(body.requestId)&&['chat','email-check','payment-review'].includes(body.type));
 if(body.type==='chat'){check(str(body.content,8000)&&body.content.trim()&&identifier(body.agent));check(!body.chatId||UUID.test(body.chatId));check(!body.projectId||UUID.test(body.projectId));const attachments=body.attachments||[];check(Array.isArray(attachments)&&attachments.length<=5);let size=0;for(const a of attachments){check(str(a.name,120)&&/^[^\\/:*?"<>|\x00-\x1f]+\.(txt|md|csv|json|html|css|js|ts|tsx|jsx|lua|xml|ini|cfg|log|yaml|yml|sql|py|cs|svg)$/i.test(a.name)&&str(a.content,60000)&&!a.content.includes('\0'));size+=a.content.length;}check(size<=180000);return {content:body.content,agent:body.agent,chatId:body.chatId||null,projectId:body.projectId||null,attachments:attachments.map(a=>({name:a.name,content:a.content}))};}
 if(body.type==='payment-review'){check(/^[a-f0-9]{64}$/.test(body.id)&&['confirmed','excluded'].includes(body.review));if(body.review==='confirmed')check(Number.isFinite(body.amount)&&body.amount>0&&body.amount<=1e12&&/^[A-Z]{3}$/.test(body.currency)&&['income','expense'].includes(body.kind)&&/^\d{4}-\d{2}-\d{2}$/.test(body.date));return {id:body.id,review:body.review,...(body.review==='confirmed'?{amount:body.amount,currency:body.currency,date:body.date,kind:body.kind,importLedger:body.importLedger===true}:{})};}
 return {};
}
export function createApp({directory,origin,development=false,trustProxy=false}){
 const address=new URL(origin);check(address.origin===origin&&(address.protocol==='https:'||(development&&address.hostname==='127.0.0.1')),'PUBLIC_URL harus origin HTTPS.');
 const db=openStore(directory),limits=new Map();let loginActive=0;
 const rate=(key,max,period)=>{const now=Date.now();if(limits.size>5000){for(const [k,v]of limits)if(v.until<now)limits.delete(k);if(limits.size>5000)check(false,'Server sibuk. Coba lagi nanti.',429);}let value=limits.get(key);if(!value||value.until<now){value={count:0,until:now+period};limits.set(key,value);}check(++value.count<=max,'Terlalu banyak percobaan. Coba lagi nanti.',429);};
 const expire=()=>{const now=Date.now();db.prepare('DELETE FROM sessions WHERE expires<?').run(now);db.prepare('DELETE FROM pairing WHERE expires<?').run(now);db.prepare("UPDATE jobs SET status='interrupted',error='PC terputus saat bekerja. Tinjau hasil lokal sebelum membuat tugas baru.',updated=? WHERE status='running' AND lease_until<?").run(now,now);};
 const mobile=req=>{const cookie=req.headers.cookie||'';const raw=cookie.split(';').map(s=>s.trim()).find(s=>s.startsWith('__Host-ditasha_session='))?.split('=')[1];const session=raw&&db.prepare('SELECT token FROM sessions WHERE token=? AND expires>?').get(hash(raw),Date.now());check(session,'Login diperlukan.',401);return session;};
 const pc=req=>{const raw=/^Bearer ([a-f0-9]{64})$/.exec(req.headers.authorization||'')?.[1];const device=raw&&db.prepare('SELECT * FROM devices WHERE token=? AND revoked=0').get(hash(raw));check(device,'PC belum dipasangkan atau akses dicabut.',401);db.prepare('UPDATE devices SET last_seen=? WHERE id=?').run(Date.now(),device.id);return device;};
 const mutation=req=>{check(req.headers.origin===origin&&req.headers['x-ditasha-request']==='1','Origin permintaan ditolak.',403);};
 const body=async(req,limit=8000000)=>{check((req.headers['content-type']||'').split(';')[0]==='application/json','Gunakan JSON.',415);let n=0;const chunks=[];for await(const chunk of req){n+=chunk.length;check(n<=limit,'Permintaan terlalu besar.',413);chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{check(false,'JSON tidak valid.');}};
 const file=(res,name,bytes,mime)=>{res.writeHead(200,{'Content-Type':mime,'Content-Disposition':'attachment; filename="'+name+'"','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(bytes);};
 const server=createServer(async(req,res)=>{
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");
  try{
   expire();const url=new URL(req.url,'http://local'),path=url.pathname,method=req.method;const ip=trustProxy?String(req.headers['x-forwarded-for']||req.socket.remoteAddress).split(',')[0].trim():req.socket.remoteAddress;
   if(path==='/health'&&method==='GET')return json(res,200,{ok:true});
   if(method==='GET'&&['/','/app.js','/style.css','/logo.svg'].includes(path)){const names={'/':'index.html','/app.js':'app.js','/style.css':'style.css','/logo.svg':'logo.svg'},types={'/':'text/html; charset=utf-8','/app.js':'text/javascript; charset=utf-8','/style.css':'text/css; charset=utf-8','/logo.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[path],'Cache-Control':'no-store'});return res.end(readFileSync(join(root,'public',names[path])));}
   if(path==='/api/login'&&method==='POST'){
    mutation(req);rate('login:'+ip,10,600000);rate('login-total',60,600000);check(loginActive<4,'Coba lagi sebentar.',429);const data=await body(req,3000);check(str(data.username,60)&&str(data.password,128),'Login tidak valid.',401);const owner=db.prepare('SELECT * FROM owner WHERE id=1').get();check(owner,'Akun pemilik belum disiapkan. Jalankan admin.mjs init di server.',503);loginActive++;let valid;try{valid=await verifyPassword(data.password,owner.password);}finally{loginActive--;}check(valid&&data.username===owner.username,'Username atau password salah.',401);const raw=token();db.prepare('INSERT INTO sessions VALUES (?,?)').run(hash(raw),Date.now()+7*86400000);res.setHeader('Set-Cookie',`__Host-ditasha_session=${raw}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`);return json(res,200,{ok:true});
   }
   if(path==='/api/pc/pair'&&method==='POST'){
    rate('pair:'+ip,5,60000);const data=await body(req,1000);check(/^\d{8}$/.test(data.code)&&str(data.name,80)&&data.name.trim());const code=db.prepare('SELECT * FROM pairing WHERE code=? AND expires>?').get(hash(data.code),Date.now());check(code,'Kode pairing salah, kedaluwarsa, atau sudah dipakai.',401);const id=randomUUID(),raw=token();db.exec('BEGIN IMMEDIATE');try{db.prepare('DELETE FROM pairing WHERE code=?').run(hash(data.code));db.prepare('UPDATE devices SET revoked=1 WHERE revoked=0').run();db.prepare("UPDATE jobs SET status='interrupted',error='PC diganti. Tinjau hasil pada PC sebelumnya.',updated=? WHERE status='running'").run(Date.now());db.prepare('INSERT INTO devices(id,name,token,last_seen) VALUES (?,?,?,?)').run(id,data.name,hash(raw),Date.now());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,200,{id,token:raw});
   }
   if(path.startsWith('/api/pc/')){
    check(method==='POST','Metode tidak didukung.',405);const device=pc(req),data=await body(req);
    if(path==='/api/pc/snapshot'){const clean=cleanSnapshot(data);const serialized=JSON.stringify(clean);check(Buffer.byteLength(serialized)<=7500000,'Snapshot terlalu besar.',413);db.prepare('INSERT INTO cache VALUES (1,?,?,?) ON CONFLICT(id) DO UPDATE SET device_id=excluded.device_id,data=excluded.data,updated=excluded.updated').run(device.id,serialized,Date.now());return json(res,200,{saved:true});}
    if(path==='/api/pc/claim'){
     if(db.prepare("SELECT id FROM jobs WHERE status='running'").get())return json(res,200,{job:null});
     const job=db.prepare("SELECT * FROM jobs WHERE status='queued' ORDER BY created LIMIT 1").get();if(!job)return json(res,200,{job:null});const lease=token(),now=Date.now();db.prepare("UPDATE jobs SET status='running',device_id=?,lease=?,lease_until=?,updated=?,progress='Amii menerima tugas dari ponsel' WHERE id=? AND status='queued'").run(device.id,hash(lease),now+600000,now,job.id);return json(res,200,{job:{id:job.id,type:job.type,request:JSON.parse(job.request),lease}});
    }
    if(path==='/api/pc/recover'){return json(res,200,{jobs:db.prepare("SELECT id FROM jobs WHERE device_id=? AND status IN ('running','interrupted') ORDER BY created DESC LIMIT 100").all(device.id)});}
    if(path==='/api/pc/reconcile'){check(UUID.test(data.id)&&['completed','failed'].includes(data.status)&&str(data.result||'',1000000)&&str(data.error||'',1000));const job=db.prepare('SELECT status FROM jobs WHERE id=? AND device_id=?').get(data.id,device.id);check(job,'Tugas bukan milik PC ini.',409);if(['completed','failed'].includes(job.status))return json(res,200,{saved:true,duplicate:true});check(['running','interrupted'].includes(job.status),'Status tugas tidak dapat disinkronkan.',409);db.prepare('UPDATE jobs SET status=?,result=?,error=?,progress=?,updated=? WHERE id=?').run(data.status,data.result||'',data.error||'','Hasil dipulihkan dari catatan PC',Date.now(),data.id);return json(res,200,{saved:true});}
    if(path==='/api/pc/heartbeat'){if(data.jobId){check(UUID.test(data.jobId)&&str(data.lease,64)&&str(data.progress,200));const update=db.prepare("UPDATE jobs SET lease_until=?,progress=?,updated=? WHERE id=? AND status='running' AND device_id=? AND lease=?").run(Date.now()+600000,data.progress,Date.now(),data.jobId,device.id,hash(data.lease));check(update.changes,'Tugas tidak lagi aktif.',409);}return json(res,200,{ok:true});}
    if(path==='/api/pc/complete'){
     check(UUID.test(data.id)&&str(data.lease,64)&&['completed','failed','interrupted'].includes(data.status)&&str(data.result||'',1000000)&&str(data.error||'',1000));const job=db.prepare('SELECT * FROM jobs WHERE id=? AND device_id=? AND lease=?').get(data.id,device.id,hash(data.lease));check(job,'Tugas atau lease tidak cocok.',409);if(['completed','failed','interrupted'].includes(job.status)){check(job.status===data.status,'Status akhir berbeda.',409);return json(res,200,{saved:true,duplicate:true});}check(job.status==='running','Tugas tidak lagi berjalan.',409);db.prepare('UPDATE jobs SET status=?,result=?,error=?,progress=?,updated=? WHERE id=?').run(data.status,data.result||'',data.error||'',data.status==='completed'?'Hasil selesai':'Perlu ditinjau',Date.now(),job.id);return json(res,200,{saved:true});}
    check(false,'Endpoint tidak ditemukan.',404);
   }
   mobile(req);if(method==='POST')mutation(req);
   if(path==='/api/logout'&&method==='POST'){const session=mobile(req);db.prepare('DELETE FROM sessions WHERE token=?').run(session.token);res.setHeader('Set-Cookie','__Host-ditasha_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0');return json(res,200,{ok:true});}
   if(path==='/api/state'&&method==='GET'){
    const cached=db.prepare('SELECT * FROM cache WHERE id=1').get(),device=db.prepare('SELECT id,name,last_seen FROM devices WHERE revoked=0').get();let snapshot=cached?JSON.parse(cached.data):null;if(snapshot?.report)snapshot={...snapshot,report:{available:true}};const jobs=db.prepare('SELECT id,type,request,status,progress,result,error,created,updated FROM jobs ORDER BY created DESC LIMIT 100').all().map(j=>({...j,request:JSON.parse(j.request)}));return json(res,200,{device:device?{...device,online:Date.now()-device.last_seen<45000}:null,snapshot,updated:cached?.updated||0,jobs});
   }
   if(path==='/api/pair/create'&&method==='POST'){const code=String(randomInt(10000000,100000000));db.prepare('DELETE FROM pairing').run();db.prepare('INSERT INTO pairing VALUES (?,?)').run(hash(code),Date.now()+600000);return json(res,200,{code,expires:Date.now()+600000});}
   if(path==='/api/device/revoke'&&method==='POST'){db.prepare('UPDATE devices SET revoked=1').run();db.prepare("UPDATE jobs SET status='interrupted',error='Akses PC dicabut.',updated=? WHERE status='running'").run(Date.now());return json(res,200,{ok:true});}
   if(path==='/api/tasks'&&method==='POST'){rate('tasks',30,60000);const data=await body(req,800000),request=taskRequest(data);const previous=db.prepare('SELECT id,request,type FROM jobs WHERE request_id=?').get(data.requestId);if(previous){check(previous.type===data.type&&previous.request===JSON.stringify(request),'ID permintaan dipakai untuk tugas lain.',409);return json(res,200,{id:previous.id,duplicate:true});}check(db.prepare('SELECT COUNT(*) AS n FROM jobs').get().n<10000,'Arsip tugas mencapai 10.000. Backup dan kelola data server dahulu.',409);if(data.type==='chat'){const snapshot=db.prepare('SELECT data FROM cache WHERE id=1').get();check(snapshot,'Hubungkan PC dan lakukan sync pertama dahulu.',409);const clean=JSON.parse(snapshot.data);check(clean.employees.some(e=>e.id===request.agent),'Karyawan tidak ditemukan.');if(request.chatId)check(clean.chats.some(c=>c.id===request.chatId),'Percakapan belum tersinkron.');if(request.projectId)check(clean.projects.some(p=>p.id===request.projectId),'Proyek belum tersinkron.');}const id=randomUUID(),now=Date.now();db.prepare('INSERT INTO jobs(id,request_id,type,request,created,updated) VALUES (?,?,?,?,?,?)').run(id,data.requestId,data.type,JSON.stringify(request),now,now);return json(res,201,{id});}
   if(/^\/api\/tasks\/[^/]+\/cancel$/.test(path)&&method==='POST'){const id=path.split('/')[3];check(UUID.test(id));const changed=db.prepare("UPDATE jobs SET status='cancelled',updated=? WHERE id=? AND status='queued'").run(Date.now(),id);check(changed.changes,'Hanya tugas yang masih antre dapat dibatalkan.',409);return json(res,200,{ok:true});}
   if(path==='/api/report'&&method==='GET'){const row=db.prepare('SELECT data FROM cache WHERE id=1').get();const report=row&&JSON.parse(row.data).report;check(report,'Excel belum tersinkron dari PC.',404);return file(res,'Lora-Achi.xlsx',Buffer.from(report.base64,'base64'),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
   if(/^\/api\/tasks\/[^/]+\/files\/\d+$/.test(path)&&method==='GET'){const [,,,id,,index]=path.split('/');const job=db.prepare("SELECT result FROM jobs WHERE id=? AND status='completed'").get(id);check(job,'Hasil tidak ditemukan.',404);const files=[...job.result.matchAll(/```[^\n]*filename=([^\s\n]+)[^\n]*\n([\s\S]*?)\n```/g)].map(m=>({name:m[1].replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,100),content:m[2]}));const chosen=files[Number(index)];check(chosen&&chosen.name&&!/^\.+$/.test(chosen.name),'File tidak ditemukan.',404);return file(res,chosen.name,Buffer.from(chosen.content),'application/octet-stream');}
   check(false,'Endpoint tidak ditemukan.',404);
  }catch(e){if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'Operasi server belum berhasil.'});else res.end();}
 });server.requestTimeout=30000;server.headersTimeout=15000;server.maxHeadersCount=50;return {server,db,close:()=>new Promise(resolve=>server.close(()=>{db.close();resolve();}))};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const app=createApp({directory:process.env.DATA_DIR||'/data',origin:process.env.PUBLIC_URL||'https://workspace.gremoryy.my.id',trustProxy:process.env.TRUST_PROXY==='1'});app.server.listen(Number(process.env.PORT||8787),'0.0.0.0',()=>console.log('DITASHA sync server listening'));for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>app.close().then(()=>process.exit(0)));}
