const {chromium}=await import(process.env.DITASHA_PLAYWRIGHT_IMPORT||'playwright');
import {createApp} from '../server.mjs';
import {passwordHash,hash} from '../store.mjs';
import {mkdtempSync,rmSync,mkdirSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
const output=process.env.DITASHA_UI_OUTPUT||'phone-preview';mkdirSync(output,{recursive:true});
const directory=mkdtempSync(join(tmpdir(),'ditasha-ui-'));const origin='http://127.0.0.1:4189';const app=createApp({directory,origin,development:true});await new Promise(r=>app.server.listen(4189,'127.0.0.1',r));
app.db.prepare('INSERT INTO owner VALUES(1,?,?)').run('foxu',await passwordHash('fixture-password-long'));
const deviceId=randomUUID(),deviceToken='a'.repeat(64);app.db.prepare('INSERT INTO devices(id,name,token,last_seen) VALUES(?,?,?,?)').run(deviceId,'PC Foxu',hash(deviceToken),Date.now());
const pc=async(path,data={})=>{const res=await fetch(origin+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+deviceToken},body:JSON.stringify(data)});assert.equal(res.status,200);return res.json()};
await pc('/api/pc/snapshot',{chats:[],messages:[],projects:[],employees:[{id:'general',name:'Amii',role:'Koordinator',model:'free-model',provider:'openrouter'},{id:'web',name:'Sora',role:'Web developer',model:'code-model',provider:'groq'}],money:{transactions:[{id:'money-test',date:'2026-10-07',kind:'expense',amount:100000,category:'Server',note:'Hosting'}]},mail:{lastRun:'2026-10-07T13:00:00Z',total:153,pending:1,payments:[{id:'b'.repeat(64),subject:'Hosting receipt <img src=x onerror=alert(1)>',account:'foxu@example.test',review:'pending',paymentType:'Receipt',amount:100000,currency:'IDR'}]}});
const browser=await chromium.launch({headless:true,executablePath:process.env.DITASHA_CHROME_EXECUTABLE||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(origin);await page.locator('input[name=username]').fill('foxu');await page.locator('input[name=password]').fill('fixture-password-long');await page.getByRole('button',{name:'Masuk ke workspace',exact:true}).click();await page.getByText('Kantormu ikut ke mana saja.').waitFor();
 await page.screenshot({path:join(output,'home.png'),fullPage:true});
 await page.getByRole('button',{name:'Chat',exact:true}).click();await page.locator('#draft').fill('Buat landing page <script>alert(1)</script>');await page.locator('#files').setInputFiles({name:'brief.md',mimeType:'text/plain',buffer:Buffer.from('Project brief')});await page.getByText('brief.md',{exact:true}).waitFor();await page.screenshot({path:join(output,'chat.png'),fullPage:true});await page.getByRole('button',{name:'Kirim ke Amii',exact:true}).click();await page.getByText('Buat landing page <script>alert(1)</script>',{exact:true}).waitFor();
 const claimed=(await pc('/api/pc/claim')).job;assert(claimed);assert.equal(claimed.request.attachments[0].content,'Project brief');await pc('/api/pc/complete',{id:claimed.id,lease:claimed.lease,status:'completed',result:'```html filename=index.html\n<h1>DITASHA</h1>\n```'});
 await page.reload();await page.getByText('Lihat hasil tim',{exact:true}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'index.html',exact:true}).click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'index.html');assert.equal(readFileSync(await download.path(),'utf8'),'<h1>DITASHA</h1>');
 await page.getByRole('button',{name:'Lora/Achi',exact:true}).click();await page.getByText('Hosting receipt <img src=x onerror=alert(1)>',{exact:true}).waitFor();assert.equal(await page.locator('.payment img').count(),0);
 await page.screenshot({path:join(output,'reports.png'),fullPage:true});await page.getByRole('button',{name:'Tinjau pembayaran',exact:true}).click();await page.locator('input[name=date]').fill('2026-10-07');await page.getByRole('button',{name:'Konfirmasi & kirim ke Achi',exact:true}).click();await page.getByText('Kantormu ikut ke mana saja.').waitFor();
 await page.getByRole('button',{name:'Perangkat',exact:true}).click();await page.getByRole('button',{name:'Buat kode pairing',exact:true}).click();assert.match(await page.locator('.pair-code').textContent(),/\d{8}/);
 await page.screenshot({path:join(output,'devices.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('Phone UI passed: real cookie login, task queue, safe text, payment review and pairing at 390px.');
}finally{await browser.close();await app.close();rmSync(directory,{recursive:true,force:true})}
