'use client';
import {AssistantPerson} from './assistant-person';
import {jobActivity} from '@/lib/assignment';
import {OfficeFloor} from './office-floor';
import {officeLayout} from '@/lib/office-motion';
import type {OfficePositions,OfficeEngine} from '@/lib/office-engine';
import {type Employee} from '@/lib/workspace';
import {MessageSquare,Maximize2,Sparkles,Plus} from 'lucide-react';
export function Person({index,working=false,walkingFrame=null,facing=1,className=''}:{index:number;working?:boolean;walkingFrame?:number|null;facing?:number;className?:string}){
 return <AssistantPerson index={index} working={working} frame={walkingFrame} facing={facing} className={className}/>;
}
export function Office({employees,onAdd,onChoose,onExpand,connected,busy,motion,compact=false}:{employees:Employee[];onAdd:()=>void;onChoose:(id:string)=>void;onExpand?:()=>void;connected:boolean;busy:boolean;activeAgent?:string;motion:{board:OfficeEngine['board'];positions:OfficePositions;enabled:boolean;setEnabled:(value:boolean)=>void};compact?:boolean}){
 const layout=officeLayout(employees.length);
 return <section className={'office-section unified-office '+(compact?'compact':'')} aria-label="Kantor bersama DITASHA">
 <div className="office-heading"><div><p className="eyebrow teal">DITASHA VIRTUAL OFFICE · {employees.length} KARYAWAN</p><h2>Satu kantor. Seluruh tim.</h2></div><div className="office-heading-actions"><button className="primary add-employee" disabled={busy} onClick={onAdd}><Plus size={16}/> Tambah karyawan</button>{onExpand&&<button className="office-expand" onClick={onExpand} aria-label="Buka kantor virtual"><Maximize2 size={17}/></button>}</div></div>
 <div className="office-navigation"><label className="movement-toggle"><input type="checkbox" checked={motion.enabled} onChange={e=>motion.setEnabled(e.target.checked)}/> Gerak karakter</label><span className="office-mode"><Sparkles size={14}/>{connected?'Siap menerima tugas':'Menunggu koneksi AI'}</span><span className="shared-office-count">{employees.length} meja · Kantor bersama</span></div>
 <div className="task-board-panel" aria-live="polite"><div><strong>Papan tugas Amii</strong><span>{motion.board.length?'Satu brief · '+motion.board.length+' kontribusi':'Berikan tugas ke Amii untuk memulai'}</span></div>{motion.board.length>0&&<ol>{motion.board.map((task,i)=>{const worker=employees.find(e=>e.id===task.employee_id);return <li key={task.employee_id} className={'board-task '+task.status}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{worker?.name||'Karyawan'} <small>{worker?.role}</small></strong><p title={task.brief}>{task.brief}</p></div><em>{task.status==='done'?'Selesai':task.status==='ready'?'Siap · menunggu tim':task.status==='working'?'Bekerja':task.status==='failed'?'Terhenti':'Menunggu giliran'}</em></li>;})}</ol>}</div>
 <div className="office-viewport"><div className="office-scene shared-scene" style={{'--world-height':layout.height+'px'} as React.CSSProperties}><OfficeFloor employees={employees}/>
 {employees.map((a,i)=>{const state=motion.positions[a.id],desk=layout.desks[i],phase=state?.phase;return <button key={a.id} disabled={busy} onClick={()=>onChoose(a.id)} className={'office-worker moving-worker '+(phase==='working'?'is-working ':'')+(state?.walkingFrame!==null&&state?.walkingFrame!==undefined?'is-walking ':'')} style={{left:(state?.point.x??desk.x/10)+'%',top:(state?.point.y??(desk.y+95)/layout.height*100)+'%','--person-color':a.color,'--depth':Math.round(state?.point.y??50)} as React.CSSProperties} aria-label={'Chat dengan '+a.name+', '+a.role}><span className="worker-activity">{phase==='assigning'?'Menempelkan tugas di papan':phase==='reporting'?'Melapor ke Amii':phase==='receiving'?a.id==='general'?'Menunggu laporan':'Mengambil tugas di papan':phase==='returning'?'Kembali ke meja':phase==='ready'?'Selesai · menunggu rekan tim':phase==='queued'?'Menunggu tugas di papan':phase==='working'?jobActivity(a):phase==='walking'?'Jalan-jalan':'Istirahat'}</span><Person index={a.avatar} walkingFrame={state?.walkingFrame??null} facing={state?.facing??1} working={phase==='working'}/><span className="worker-name">{a.name}<MessageSquare size={12}/></span><span className="worker-role">{a.role}</span></button>;})}
 </div></div><div className="office-roster shared-roster">{employees.map((a,i)=><button key={a.id} className="roster-item" disabled={busy} onClick={()=>onChoose(a.id)} style={{'--person-color':a.color} as React.CSSProperties}><span className="roster-number">{String(i+1).padStart(2,'0')}</span><span><strong>{a.name}</strong><small>{a.role}</small></span><MessageSquare size={15}/></button>)}</div></section>;
}
