/* Official ChatGPT plan OAuth: loopback PKCE, verified OIDC, DPAPI and Responses SSE. */
#include <winsock2.h>
#include <ws2tcpip.h>
#include <bcrypt.h>
#include "chatgpt-core.h"
#define CG_MAX_ACCOUNTS 12
#define CG_USAGE L"https://chatgpt.com/#settings/Usage"
typedef struct CgAccount {char *client,*sub,*email,*access,*refresh,*identity,*scope,*models,*general,*coding;long long expiry;BOOL welcomed;} CgAccount;
typedef struct CgStore {char *host,*active;CgAccount accounts[CG_MAX_ACCOUNTS];int count;} CgStore;
typedef struct CgJob {HWND window;unsigned long id;char *op,*payload,*model;BOOL coding;} CgJob;
static volatile LONG cg_control=0,cg_cancel=0;
static void cg_free_account(CgAccount *a){cg_clear(a->client);cg_clear(a->sub);cg_clear(a->email);cg_clear(a->access);cg_clear(a->refresh);cg_clear(a->identity);cg_clear(a->scope);cg_clear(a->models);cg_clear(a->general);cg_clear(a->coding);memset(a,0,sizeof(*a));}
static void cg_free_store(CgStore *s){cg_clear(s->host);cg_clear(s->active);for(int i=0;i<s->count;i++)cg_free_account(&s->accounts[i]);memset(s,0,sizeof(*s));}
static BOOL cg_sha(const BYTE *data,ULONG n,BYTE hash[32]){BCRYPT_ALG_HANDLE alg=NULL;BOOL ok=BCryptOpenAlgorithmProvider(&alg,BCRYPT_SHA256_ALGORITHM,NULL,0)>=0&&BCryptHash(alg,NULL,0,(PUCHAR)data,n,hash,32)>=0;if(alg)BCryptCloseAlgorithmProvider(alg,0);return ok;}
static char *cg_b64(const BYTE *data,DWORD n){DWORD size=0;if(!CryptBinaryToStringA(data,n,CRYPT_STRING_BASE64|CRYPT_STRING_NOCRLF,NULL,&size))return NULL;char *out=malloc(size);if(!out)return NULL;if(!CryptBinaryToStringA(data,n,CRYPT_STRING_BASE64|CRYPT_STRING_NOCRLF,out,&size)){free(out);return NULL;}for(char *p=out;*p;p++){if(*p=='+')*p='-';else if(*p=='/')*p='_';else if(*p=='='){*p=0;break;}}return out;}
static BYTE *cg_unb64(const char *s,DWORD *n){size_t len=strlen(s);if(!len||len>200000||len%4==1)return NULL;char *copy=calloc(len+5,1);if(!copy)return NULL;memcpy(copy,s,len);for(size_t i=0;i<len;i++){if(copy[i]=='-')copy[i]='+';else if(copy[i]=='_')copy[i]='/';else if(!((copy[i]>='a'&&copy[i]<='z')||(copy[i]>='A'&&copy[i]<='Z')||(copy[i]>='0'&&copy[i]<='9'))){free(copy);return NULL;}}while(len%4)copy[len++]='=';
 DWORD size=0;BYTE *out=NULL;if(CryptStringToBinaryA(copy,(DWORD)len,CRYPT_STRING_BASE64,NULL,&size,NULL,NULL)){out=malloc((size_t)size+1);if(out&&!CryptStringToBinaryA(copy,(DWORD)len,CRYPT_STRING_BASE64,out,&size,NULL,NULL)){free(out);out=NULL;}if(out){out[size]=0;*n=size;}}free(copy);return out;}
static char *cg_random(void){BYTE bytes[32];if(BCryptGenRandom(NULL,bytes,sizeof(bytes),BCRYPT_USE_SYSTEM_PREFERRED_RNG)<0)return NULL;char *s=cg_b64(bytes,sizeof(bytes));SecureZeroMemory(bytes,sizeof(bytes));return s;}
static char *cg_host_id(void){
 BYTE b[16];if(BCryptGenRandom(NULL,b,sizeof(b),BCRYPT_USE_SYSTEM_PREFERRED_RNG)<0)return NULL;b[6]=(BYTE)((b[6]&15)|64);b[8]=(BYTE)((b[8]&63)|128);char *host=malloc(46);if(host)snprintf(host,46,"urn:uuid:%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7],b[8],b[9],b[10],b[11],b[12],b[13],b[14],b[15]);SecureZeroMemory(b,sizeof(b));return host;
}
static HANDLE cg_mutex(void){BYTE hash[32];if(!cg_sha((BYTE*)data_root,(ULONG)(wcslen(data_root)*sizeof(WCHAR)),hash))return NULL;WCHAR name[128];swprintf(name,128,L"Local\\DITASHA-ChatGPT-%02x%02x%02x%02x%02x%02x%02x%02x",hash[0],hash[1],hash[2],hash[3],hash[4],hash[5],hash[6],hash[7]);HANDLE m=CreateMutexW(NULL,FALSE,name);if(!m)return NULL;DWORD r=WaitForSingleObject(m,120000);if(r!=WAIT_OBJECT_0&&r!=WAIT_ABANDONED){CloseHandle(m);return NULL;}return m;}
static void cg_unlock(HANDLE m){if(m){ReleaseMutex(m);CloseHandle(m);}}
static BOOL cg_load(CgStore *s){
 memset(s,0,sizeof(*s));DWORD n=0;BOOL missing=FALSE;char *encrypted=read_local(L"chatgpt.accounts",1000000,&n,&missing);if(missing)return TRUE;if(!encrypted)return FALSE;
 DATA_BLOB in={n,(BYTE*)encrypted},out={0};BOOL ok=CryptUnprotectData(&in,NULL,NULL,NULL,NULL,CRYPTPROTECT_UI_FORBIDDEN,&out);free(encrypted);if(!ok)return FALSE;
 char *plain=calloc((size_t)out.cbData+1,1);if(plain)memcpy(plain,out.pbData,out.cbData);SecureZeroMemory(out.pbData,out.cbData);LocalFree(out.pbData);if(!plain)return FALSE;
 CgJson j=cg_json(plain);int array=j.t?cg_field(&j,0,"accounts"):-1;ok=array>=0&&j.t[array].type==JSMN_ARRAY&&j.t[array].size<=CG_MAX_ACCOUNTS;
 if(ok){s->host=cg_get(&j,0,"host");s->active=cg_get(&j,0,"active");if(!s->host||!s->active)ok=FALSE;for(int i=array+1;ok&&i<j.n&&j.t[i].start<j.t[array].end;i=cg_skip(&j,i)){CgAccount *a=&s->accounts[s->count++];a->client=cg_get(&j,i,"client");a->sub=cg_get(&j,i,"sub");a->email=cg_get(&j,i,"email");a->access=cg_get(&j,i,"access");a->refresh=cg_get(&j,i,"refresh");a->identity=cg_get(&j,i,"identity");a->scope=cg_get(&j,i,"scope");a->models=cg_raw(&j,cg_field(&j,i,"models"));a->general=cg_get(&j,i,"general");a->coding=cg_get(&j,i,"coding");a->expiry=cg_number(&j,i,"expiry");a->welcomed=cg_number(&j,i,"welcomed")==1;if(!a->client||strncmp(a->client,"oaiapp_",7)||!a->sub||!a->email||!a->access||!a->refresh||!a->identity||!a->scope||!a->models||!a->general||!a->coding)ok=FALSE;}}
 free(j.t);cg_clear(plain);if(!ok)cg_free_store(s);return ok;
}
static BOOL cg_save(CgStore *s){
 if(!cg_host_valid(s->host)){char *host=cg_host_id();if(!host)return FALSE;free(s->host);s->host=host;}if(!s->active)s->active=_strdup("");
 char *qh=cg_quote(s->host),*qa=cg_quote(s->active);char *text=calloc(1000000,1);if(!qh||!qa||!text){free(qh);free(qa);free(text);return FALSE;}size_t used=(size_t)snprintf(text,1000000,"{\"host\":%s,\"active\":%s,\"accounts\":[",qh,qa);free(qh);free(qa);
 for(int i=0;i<s->count;i++){CgAccount *a=&s->accounts[i];char *q[9]={cg_quote(a->client),cg_quote(a->sub),cg_quote(a->email),cg_quote(a->access),cg_quote(a->refresh),cg_quote(a->identity),cg_quote(a->scope),cg_quote(a->general),cg_quote(a->coding)};BOOL good=TRUE;for(int k=0;k<9;k++)if(!q[k])good=FALSE;
  int n=good?snprintf(text+used,1000000-used,"%s{\"client\":%s,\"sub\":%s,\"email\":%s,\"access\":%s,\"refresh\":%s,\"identity\":%s,\"scope\":%s,\"general\":%s,\"coding\":%s,\"expiry\":%lld,\"welcomed\":%d,\"models\":%s}",i?",":"",q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],a->expiry,a->welcomed?1:0,a->models?a->models:"[]"):-1;for(int k=0;k<9;k++)cg_clear(q[k]);if(n<0||(size_t)n>=1000000-used){cg_clear(text);return FALSE;}used+=(size_t)n;
 }if(used+3>=1000000){cg_clear(text);return FALSE;}strcpy(text+used,"]}");DATA_BLOB in={(DWORD)strlen(text),(BYTE*)text},out={0};BOOL ok=CryptProtectData(&in,L"DITASHA ChatGPT accounts",NULL,NULL,NULL,CRYPTPROTECT_UI_FORBIDDEN,&out);if(ok){ok=write_local(L"chatgpt.accounts",out.pbData,out.cbData,FALSE);SecureZeroMemory(out.pbData,out.cbData);LocalFree(out.pbData);}cg_clear(text);return ok;
}
static CgAccount *cg_active(CgStore *s){for(int i=0;i<s->count;i++)if(s->active&&!strcmp(s->accounts[i].client,s->active))return &s->accounts[i];return NULL;}
static BOOL cg_using(void){char *s=read_local(L"ai.provider",32,NULL,NULL);BOOL yes=s&&!strcmp(s,"chatgpt");free(s);return yes;}
static char *cg_http(const WCHAR *host,const WCHAR *path,const WCHAR *method,const char *body,const char *token,DWORD *status){
 HINTERNET session=NULL,connection=NULL,request=NULL;char *response=NULL;WCHAR *auth=NULL;*status=0;
 session=WinHttpOpen(L"DITASHA-Workspace/3.8",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0);if(!session)goto done;WinHttpSetTimeouts(session,15000,15000,30000,90000);
 connection=WinHttpConnect(session,host,INTERNET_DEFAULT_HTTPS_PORT,0);if(!connection)goto done;request=WinHttpOpenRequest(connection,method,path,NULL,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,WINHTTP_FLAG_SECURE);if(!request)goto done;
 DWORD policy=WINHTTP_OPTION_REDIRECT_POLICY_NEVER;if(!WinHttpSetOption(request,WINHTTP_OPTION_REDIRECT_POLICY,&policy,sizeof(policy)))goto done;
 if(token){size_t n=strlen(token)+32;char *a=malloc(n);if(!a)goto done;snprintf(a,n,"Authorization: Bearer %s\r\n",token);auth=to_wide(a);cg_clear(a);if(!auth||!WinHttpAddRequestHeaders(request,auth,(DWORD)-1,WINHTTP_ADDREQ_FLAG_ADD|WINHTTP_ADDREQ_FLAG_REPLACE))goto done;}
 const WCHAR *headers=!wcscmp(host,L"auth.openai.com")?L"Content-Type: application/x-www-form-urlencoded\r\n":L"Content-Type: application/json\r\nAccept: text/event-stream, application/json\r\n";
 DWORD length=body?(DWORD)strlen(body):0;if(!WinHttpSendRequest(request,headers,(DWORD)-1,(void*)body,length,length,0)||!WinHttpReceiveResponse(request,NULL))goto done;DWORD sn=sizeof(*status);if(!WinHttpQueryHeaders(request,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,NULL,status,&sn,NULL))goto done;
 response=calloc(1,1);DWORD total=0,available=0;while(response){if(!WinHttpQueryDataAvailable(request,&available))goto failed;if(!available)break;if(available>16000000-total)goto failed;char *grown=realloc(response,(size_t)total+available+1);if(!grown)goto failed;response=grown;DWORD received=0;if(!WinHttpReadData(request,response+total,available,&received)||!received)goto failed;total+=received;response[total]=0;}goto done;
 failed:cg_clear(response);response=NULL;
 done:if(auth){SecureZeroMemory(auth,wcslen(auth)*sizeof(WCHAR));free(auth);}if(request)WinHttpCloseHandle(request);if(connection)WinHttpCloseHandle(connection);if(session)WinHttpCloseHandle(session);return response;
}
static BOOL cg_verify_token(const char *jwt,const char *client,const char *nonce,const char *trusted_jwks,char **sub,char **email){
 BOOL ok=FALSE;char *copy=_strdup(jwt),*kid=NULL,*alg=NULL;BYTE *header=NULL,*payload=NULL,*sig=NULL;CgJson h={0},p={0},keys={0};BCRYPT_ALG_HANDLE rsa=NULL;BCRYPT_KEY_HANDLE pub=NULL;
 if(!copy||strlen(copy)>200000)goto done;char *dot=strchr(copy,'.');if(!dot)goto done;*dot++=0;char *last=strchr(dot,'.');if(!last||strchr(last+1,'.'))goto done;*last++=0;DWORD hn=0,pn=0,sn=0;header=cg_unb64(copy,&hn);payload=cg_unb64(dot,&pn);sig=cg_unb64(last,&sn);if(!header||!payload||!sig||memchr(header,0,hn)||memchr(payload,0,pn))goto done;
 h=cg_json((char*)header);p=cg_json((char*)payload);if(!h.t||!p.t)goto done;alg=cg_get(&h,0,"alg");kid=cg_get(&h,0,"kid");if(!alg||strcmp(alg,"RS256")||!kid||!cg_claims(&p,client,nonce,(long long)time(NULL)))goto done;
 keys=cg_json(trusted_jwks);int array=keys.t?cg_field(&keys,0,"keys"):-1;if(array<0||keys.t[array].type!=JSMN_ARRAY)goto done;
 for(int i=array+1;i<keys.n&&keys.t[i].start<keys.t[array].end;i=cg_skip(&keys,i)){char *k=cg_get(&keys,i,"kid"),*type=cg_get(&keys,i,"kty"),*use=cg_get(&keys,i,"use"),*ka=cg_get(&keys,i,"alg");BOOL match=k&&!strcmp(k,kid)&&type&&!strcmp(type,"RSA")&&(!use||!strcmp(use,"sig"))&&(!ka||!strcmp(ka,"RS256"));free(k);free(type);free(use);free(ka);if(!match)continue;
  char *ns=cg_get(&keys,i,"n"),*es=cg_get(&keys,i,"e");DWORD nn=0,en=0;BYTE *n=ns?cg_unb64(ns,&nn):NULL,*e=es?cg_unb64(es,&en):NULL;free(ns);free(es);if(!n||!e||nn<256||nn>1024||en>8||!en){free(n);free(e);goto done;}
  DWORD bn=(DWORD)sizeof(BCRYPT_RSAKEY_BLOB)+nn+en;BYTE *blob=calloc(bn,1);if(!blob){free(n);free(e);goto done;}BCRYPT_RSAKEY_BLOB *b=(BCRYPT_RSAKEY_BLOB*)blob;b->Magic=BCRYPT_RSAPUBLIC_MAGIC;b->BitLength=nn*8;b->cbPublicExp=en;b->cbModulus=nn;memcpy(blob+sizeof(*b),e,en);memcpy(blob+sizeof(*b)+en,n,nn);free(n);free(e);
  if(BCryptOpenAlgorithmProvider(&rsa,BCRYPT_RSA_ALGORITHM,NULL,0)<0||BCryptImportKeyPair(rsa,NULL,BCRYPT_RSAPUBLIC_BLOB,&pub,blob,bn,0)<0){free(blob);goto done;}free(blob);BYTE hash[32];size_t signing=(size_t)(strrchr(jwt,'.')-jwt);BCRYPT_PKCS1_PADDING_INFO padding={BCRYPT_SHA256_ALGORITHM};if(cg_sha((BYTE*)jwt,(ULONG)signing,hash)&&BCryptVerifySignature(pub,&padding,hash,32,sig,sn,BCRYPT_PAD_PKCS1)>=0){*sub=cg_get(&p,0,"sub");*email=cg_get(&p,0,"email");if(!*email)*email=_strdup("ChatGPT account");ok=*sub&&*email;}break;
 }
 done:if(pub)BCryptDestroyKey(pub);if(rsa)BCryptCloseAlgorithmProvider(rsa,0);free(h.t);free(p.t);free(keys.t);free(header);free(payload);free(sig);free(kid);free(alg);cg_clear(copy);return ok;
}
static BOOL cg_verify(const char *jwt,const char *client,const char *nonce,char **sub,char **email){
 DWORD status=0;char *jwks=cg_http(L"auth.openai.com",L"/.well-known/jwks.json",L"GET",NULL,NULL,&status);BOOL ok=status==200&&jwks&&cg_verify_token(jwt,client,nonce,jwks,sub,email);cg_clear(jwks);return ok;
}
static BOOL cg_set_tokens(CgAccount *a,const char *response,BOOL initial){
 CgJson j=cg_json(response);if(!j.t)return FALSE;char *access=cg_get(&j,0,"access_token"),*refresh=cg_get(&j,0,"refresh_token"),*identity=cg_get(&j,0,"id_token"),*scope=cg_get(&j,0,"scope"),*type=cg_get(&j,0,"token_type");long long life=cg_number(&j,0,"expires_in");BOOL ok=access&&*access&&strlen(access)<100000&&type&&!_stricmp(type,"Bearer")&&life>0&&life<=2592000&&(!initial||(identity&&refresh&&scope));
 if(ok){cg_clear(a->access);a->access=access;access=NULL;a->expiry=(long long)time(NULL)+life;if(refresh){cg_clear(a->refresh);a->refresh=refresh;refresh=NULL;}if(identity){cg_clear(a->identity);a->identity=identity;identity=NULL;}if(scope){cg_clear(a->scope);a->scope=scope;scope=NULL;}}
 cg_clear(access);cg_clear(refresh);cg_clear(identity);free(scope);free(type);free(j.t);return ok;
}
static const char *cg_renew(CgStore *s,CgAccount *a){
 if(!a||!a->access||!*a->access)return "Login ChatGPT di Pengaturan terlebih dahulu.";if(a->expiry>(long long)time(NULL)+120)return NULL;if(!a->refresh||!*a->refresh)return "Sesi ChatGPT berakhir. Login kembali di Pengaturan.";
 char *client=cg_encode(a->client),*token=cg_encode(a->refresh);char *body=NULL;if(client&&token){size_t n=strlen(client)+strlen(token)+160;body=malloc(n);if(body)snprintf(body,n,"grant_type=refresh_token&client_id=%s&refresh_token=%s&resource=https%%3A%%2F%%2Fapi.openai.com%%2Fv1",client,token);}cg_clear(client);cg_clear(token);if(!body)return "Sesi ChatGPT tidak dapat diperbarui.";
 DWORD status=0;char *response=cg_http(L"auth.openai.com",L"/api/accounts/oauth/token",L"POST",body,NULL,&status);cg_clear(body);const char *error=NULL;if(!response||status!=200||!cg_set_tokens(a,response,FALSE))error=status==400||status==401?"Sesi ChatGPT berakhir atau dicabut. Login kembali di Pengaturan.":"Tidak dapat memperbarui sesi ChatGPT. Periksa internet.";else if(!cg_save(s))error="Sesi ChatGPT belum tersimpan. Coba login kembali.";cg_clear(response);return error;
}
static BOOL cg_model_allowed(CgAccount *a,const char *model){CgJson j=cg_json(a->models);BOOL found=FALSE;if(j.t&&j.t[0].type==JSMN_ARRAY)for(int i=1;i<j.n&&j.t[i].start<j.t[0].end;i=cg_skip(&j,i)){char *slug=cg_get(&j,i,"slug");if(slug&&!strcmp(slug,model))found=TRUE;free(slug);}free(j.t);return found;}
static const char *cg_models(CgAccount *a){
 DWORD status=0;char *response=cg_http(L"api.openai.com",L"/v1/models",L"GET",NULL,a->access,&status);if(!response||status!=200){cg_clear(response);return status==401?"Sesi ChatGPT tidak valid. Login kembali.":status==403?"Akun ini belum mendapat izin penggunaan paket ChatGPT.":"Daftar model ChatGPT belum tersedia. Coba muat ulang.";}
 CgJson j=cg_json(response);int array=j.t?cg_field(&j,0,"models"):-1;char *out=calloc(100000,1);size_t used=1;int count=0;if(out)out[0]='[';
 if(out&&array>=0&&j.t[array].type==JSMN_ARRAY){for(int i=array+1;i<j.n&&j.t[i].start<j.t[array].end;i=cg_skip(&j,i)){char *v=cg_get(&j,i,"visibility"),*slug=cg_get(&j,i,"slug"),*name=cg_get(&j,i,"display_name");if(v&&!strcmp(v,"list")&&slug&&*slug&&strlen(slug)<256&&name&&strlen(name)<256){char *qs=cg_quote(slug),*qn=cg_quote(name);int n=qs&&qn?snprintf(out+used,100000-used,"%s{\"slug\":%s,\"display_name\":%s}",count?",":"",qs,qn):-1;free(qs);free(qn);if(n<0||(size_t)n>=100000-used){free(v);free(slug);free(name);count=0;break;}used+=(size_t)n;count++;}free(v);free(slug);free(name);}}
 free(j.t);cg_clear(response);if(!out||!count){free(out);return "Tidak ada model yang tersedia untuk akun ChatGPT ini.";}out[used++]=']';out[used]=0;free(a->models);a->models=out;
 CgJson list=cg_json(out);char *first=list.t?cg_get(&list,1,"slug"):NULL;free(list.t);if(!first)return "Daftar model ChatGPT tidak valid.";if(!cg_model_allowed(a,a->general?a->general:"")){free(a->general);a->general=_strdup(first);}if(!cg_model_allowed(a,a->coding?a->coding:"")){free(a->coding);a->coding=_strdup(first);}free(first);return NULL;
}
static char *cg_status(CgStore *s){
 char *selected=read_local(L"ai.provider",32,NULL,NULL);if(!selected||(strcmp(selected,"openrouter")&&strcmp(selected,"chatgpt")&&strcmp(selected,"groq")&&strcmp(selected,"gemini")&&strcmp(selected,"openai")&&strcmp(selected,"custom"))){free(selected);selected=_strdup("openrouter");}
 CgAccount *a=cg_active(s);char *result=calloc(200000,1),*active=cg_quote(s->active);if(!result||!active){free(result);free(active);free(selected);return NULL;}char *general=cg_quote(a?a->general:""),*coding=cg_quote(a?a->coding:"");if(!general||!coding){free(result);free(active);free(general);free(coding);free(selected);return NULL;}
 size_t used=(size_t)snprintf(result,200000,"{\"provider\":\"%s\",\"active\":%s,\"connected\":%s,\"permitted\":%s,\"general\":%s,\"coding\":%s,\"models\":%s,\"accounts\":[",selected?selected:"openrouter",active,a&&a->access&&*a->access?"true":"false",a&&cg_scope(a->scope,"chatgpt.tokens.use.direct")?"true":"false",general,coding,a&&a->models?a->models:"[]");free(active);free(general);free(coding);free(selected);
 for(int i=0;i<s->count;i++){CgAccount *p=&s->accounts[i];char *id=cg_quote(p->client),*email=cg_quote(p->email);int n=id&&email?snprintf(result+used,200000-used,"%s{\"id\":%s,\"email\":%s,\"signedIn\":%s}",i?",":"",id,email,p->access&&*p->access?"true":"false"):-1;free(id);free(email);if(n<0||(size_t)n>=200000-used){free(result);return NULL;}used+=(size_t)n;}if(used+4>=200000){free(result);return NULL;}strcpy(result+used,"]}");return result;
}
/* Listen only on loopback. Invalid paths/states never consume the real attempt. */
static const char *cg_login(CgStore *s,const char *selected,BOOL *welcome){
 const char *error="Login ChatGPT gagal. Coba lagi.";CgAccount *old=NULL,fresh={0};SOCKET listener=INVALID_SOCKET,peer=INVALID_SOCKET;BOOL wsa=FALSE;char *state=NULL,*nonce=NULL,*verifier=NULL,*challenge=NULL,*url=NULL,*code=NULL,*client=NULL,*body=NULL,*response=NULL;WCHAR *wide=NULL;
 if(selected&&*selected)for(int i=0;i<s->count;i++)if(!strcmp(s->accounts[i].client,selected))old=&s->accounts[i];if(selected&&*selected&&!old)return "Akun ChatGPT tidak ditemukan.";if(!old&&s->count>=CG_MAX_ACCOUNTS)return "Maksimal 12 akun ChatGPT tersimpan.";
 if(!cg_save(s))return "Identitas PC untuk ChatGPT tidak dapat disimpan.";
 WSADATA ws;if(WSAStartup(MAKEWORD(2,2),&ws))goto done;wsa=TRUE;listener=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(listener==INVALID_SOCKET)goto done;BOOL exclusive=TRUE;setsockopt(listener,SOL_SOCKET,SO_EXCLUSIVEADDRUSE,(char*)&exclusive,sizeof(exclusive));struct sockaddr_in addr={0};addr.sin_family=AF_INET;addr.sin_addr.s_addr=htonl(INADDR_LOOPBACK);addr.sin_port=0;if(bind(listener,(struct sockaddr*)&addr,sizeof(addr))||listen(listener,4))goto done;int an=sizeof(addr);if(getsockname(listener,(struct sockaddr*)&addr,&an))goto done;
 char redirect[100];snprintf(redirect,sizeof(redirect),"http://127.0.0.1:%u/auth/callback",ntohs(addr.sin_port));state=cg_random();nonce=cg_random();verifier=cg_random();BYTE hash[32];if(!state||!nonce||!verifier||!cg_sha((BYTE*)verifier,(ULONG)strlen(verifier),hash))goto done;challenge=cg_b64(hash,32);if(!challenge)goto done;
 char *r=cg_encode(redirect),*h=cg_encode(s->host),*c=cg_encode(old?old->client:"dynamic_agent_client"),*hint=old&&old->identity&&*old->identity?cg_encode(old->identity):_strdup("");size_t un=(r?strlen(r):0)+(h?strlen(h):0)+(c?strlen(c):0)+(hint?strlen(hint):0)+2000;url=malloc(un);
 if(!r||!h||!c||!hint||!url){free(r);free(h);free(c);cg_clear(hint);goto done;}
 snprintf(url,un,"https://auth.openai.com/api/accounts/authorize?client_id=%s&ext_agent_host_id=%s%s&response_type=code&redirect_uri=%s&scope=openid%%20profile%%20email%%20offline_access%%20resource.invoke%%20chatgpt.tokens.use.direct&resource=https%%3A%%2F%%2Fapi.openai.com%%2Fv1&state=%s&nonce=%s&code_challenge_method=S256&code_challenge=%s%s%s",c,h,old?"":"&agent_name_hint=DITASHA%20Workspace",r,state,nonce,challenge,*hint?"&id_token_hint=":"",hint);free(r);free(h);free(c);cg_clear(hint);wide=to_wide(url);if(!wide||(INT_PTR)ShellExecuteW(NULL,L"open",wide,NULL,NULL,SW_SHOWNORMAL)<=32){error="Browser tidak dapat dibuka. Atur browser default Windows.";goto done;}
 ULONGLONG deadline=GetTickCount64()+300000;while(GetTickCount64()<deadline&&!InterlockedCompareExchange(&cg_cancel,0,0)){
  fd_set set;FD_ZERO(&set);FD_SET(listener,&set);struct timeval timeout={1,0};if(select(0,&set,NULL,NULL,&timeout)<=0)continue;peer=accept(listener,NULL,NULL);if(peer==INVALID_SOCKET)continue;DWORD ms=2000;setsockopt(peer,SOL_SOCKET,SO_RCVTIMEO,(char*)&ms,sizeof(ms));char request[32768];int total=0;ULONGLONG peer_deadline=GetTickCount64()+4000;while(total<(int)sizeof(request)-1&&GetTickCount64()<peer_deadline&&!InterlockedCompareExchange(&cg_cancel,0,0)){int n=recv(peer,request+total,(int)sizeof(request)-1-total,0);if(n<=0)break;total+=n;request[total]=0;if(strstr(request,"\r\n\r\n"))break;}request[total]=0;
  char *space=!strncmp(request,"GET /auth/callback?",19)?strchr(request+19,' '):NULL;BOOL valid=FALSE;char *returned=NULL;
  if(space){*space=0;returned=cg_query(request+19,"state");valid=returned&&!strcmp(returned,state);}cg_clear(returned);
  const char *reply=valid?"HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n<!doctype html><title>DITASHA Workspace</title><h2>Kembali ke DITASHA Workspace</h2><p>Login sedang diverifikasi. Kamu boleh menutup tab ini.</p>":"HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\nInvalid callback";send(peer,reply,(int)strlen(reply),0);closesocket(peer);peer=INVALID_SOCKET;
  if(valid){char *denied=cg_query(request+19,"error");if(denied){cg_clear(denied);error="Login atau izin penggunaan paket ChatGPT dibatalkan.";goto done;}code=cg_query(request+19,"code");client=old?_strdup(old->client):cg_query(request+19,"client_id");SecureZeroMemory(request,sizeof(request));break;}SecureZeroMemory(request,sizeof(request));
 }
 if(InterlockedCompareExchange(&cg_cancel,0,0)){error="Login ChatGPT dibatalkan.";goto done;}if(!code||!client||strncmp(client,"oaiapp_",7)){error="Login belum selesai atau registrasi belum tersedia untuk akun ini. Coba lagi.";goto done;}
 char *cenc=cg_encode(client),*kenc=cg_encode(code),*renc=cg_encode(redirect);size_t bn=(cenc?strlen(cenc):0)+(kenc?strlen(kenc):0)+(renc?strlen(renc):0)+strlen(verifier)+200;body=malloc(bn);if(cenc&&kenc&&renc&&body)snprintf(body,bn,"grant_type=authorization_code&client_id=%s&code=%s&code_verifier=%s&redirect_uri=%s&resource=https%%3A%%2F%%2Fapi.openai.com%%2Fv1",cenc,kenc,verifier,renc);else{free(cenc);cg_clear(kenc);free(renc);goto done;}free(cenc);cg_clear(kenc);free(renc);
 DWORD status=0;response=cg_http(L"auth.openai.com",L"/api/accounts/oauth/token",L"POST",body,NULL,&status);if(status!=200||!response||!cg_set_tokens(&fresh,response,TRUE)){error="OpenAI belum menyelesaikan login. Coba masuk kembali; periksa kelayakan akun.";goto done;}
 fresh.client=_strdup(client);fresh.models=_strdup("[]");fresh.general=_strdup("");fresh.coding=_strdup("");if(!fresh.client||!fresh.models||!fresh.general||!fresh.coding||!cg_verify(fresh.identity,client,nonce,&fresh.sub,&fresh.email)){error="Identitas login ChatGPT tidak dapat diverifikasi. Sesi tidak diaktifkan.";goto done;}if(old&&strcmp(old->sub,fresh.sub)){error="Akun yang masuk berbeda dari akun tersimpan. Gunakan Tambah akun.";goto done;}
 if(old){fresh.welcomed=old->welcomed;free(fresh.general);fresh.general=_strdup(old->general);free(fresh.coding);fresh.coding=_strdup(old->coding);}
 /* Identity-only login is retained, but cannot issue AI calls. */
 const char *model_error=NULL;if(cg_scope(fresh.scope,"chatgpt.tokens.use.direct"))model_error=cg_models(&fresh);
 if(!old){for(int i=0;i<s->count;i++)if(!strcmp(s->accounts[i].client,fresh.client)){old=&s->accounts[i];if(strcmp(old->sub,fresh.sub)){error="Registrasi akun ChatGPT tidak cocok.";goto done;}break;}}
 if(old){cg_free_account(old);*old=fresh;}else s->accounts[s->count++]=fresh;memset(&fresh,0,sizeof(fresh));free(s->active);s->active=_strdup(client);if(!s->active||!cg_save(s)){error="Login ChatGPT tidak dapat disimpan di PC.";goto done;}
 CgAccount *a=cg_active(s);*welcome=a&&!a->welcomed&&cg_scope(a->scope,"chatgpt.tokens.use.direct");
 if(model_error){error=model_error;goto done;}error=NULL;
 done:if(peer!=INVALID_SOCKET)closesocket(peer);if(listener!=INVALID_SOCKET)closesocket(listener);if(wsa)WSACleanup();if(wide){SecureZeroMemory(wide,wcslen(wide)*sizeof(WCHAR));free(wide);}cg_clear(state);cg_clear(nonce);cg_clear(verifier);free(challenge);cg_clear(url);cg_clear(code);free(client);cg_clear(body);cg_clear(response);cg_free_account(&fresh);return error;
}
static BOOL cg_revoke(CgAccount *a){
 if(!a||!a->refresh||!*a->refresh)return TRUE;DWORD status=0;char *discovery=cg_http(L"auth.openai.com",L"/.well-known/openid-configuration",L"GET",NULL,NULL,&status);CgJson j=cg_json(discovery);char *endpoint=j.t?cg_get(&j,0,"revocation_endpoint"):NULL;free(j.t);cg_clear(discovery);const char *prefix="https://auth.openai.com/";if(!endpoint||strncmp(endpoint,prefix,strlen(prefix))||strchr(endpoint,'#')){free(endpoint);return FALSE;}WCHAR *path=to_wide(endpoint+strlen(prefix)-1);free(endpoint);char *token=cg_encode(a->refresh),*client=cg_encode(a->client);size_t n=(token?strlen(token):0)+(client?strlen(client):0)+100;char *body=malloc(n);if(!path||!token||!client||!body){free(path);cg_clear(token);free(client);free(body);return FALSE;}snprintf(body,n,"token=%s&token_type_hint=refresh_token&client_id=%s",token,client);cg_clear(token);free(client);char *r=cg_http(L"auth.openai.com",path,L"POST",body,NULL,&status);cg_clear(body);free(path);cg_clear(r);return status==200;
}
static char *cg_ai(CgJob *job,const char **error){
 CgStore s={0};HANDLE m=cg_mutex();char *access=NULL,*model=NULL,*response=NULL,*input=NULL,*body=NULL,*answer=NULL,*result=NULL;
 if(!m||!cg_load(&s)){*error="Akun ChatGPT tidak dapat dibaca.";goto unlock;}CgAccount *a=cg_active(&s);*error=cg_renew(&s,a);if(*error)goto unlock;if(!cg_scope(a->scope,"chatgpt.tokens.use.direct")){*error="Login tersimpan, tetapi penggunaan paket ChatGPT belum diizinkan. Login kembali atau pilih OpenRouter.";goto unlock;}const char *chosen=job->model&&*job->model?job->model:(job->coding?a->coding:a->general);if(!cg_model_allowed(a,chosen)){*error="Pilih model ChatGPT yang tersedia di Pengaturan.";goto unlock;}access=_strdup(a->access);model=_strdup(chosen);
 unlock:cg_free_store(&s);cg_unlock(m);if(*error||!access||!model)goto done;
 input=cg_input(job->payload);char *q=cg_quote(model);size_t n=(input?strlen(input):0)+(q?strlen(q):0)+100;body=malloc(n);if(!input||!q||!body){free(q);*error="Pesan ChatGPT tidak valid.";goto done;}snprintf(body,n,"{\"model\":%s,\"input\":%s,\"store\":false,\"stream\":true}",q,input);free(q);DWORD status=0;response=cg_http(L"api.openai.com",L"/v1/responses",L"POST",body,access,&status);
 if(status!=200||!response){*error=status==429||status==402?"Batas penggunaan ChatGPT tercapai. Buka Kelola penggunaan di Pengaturan. Tidak ada perpindahan otomatis ke API berbayar.":status==401?"Sesi ChatGPT dicabut atau berakhir. Login kembali.":status==403?"Akun atau workspace ini belum mengizinkan penggunaan paket ChatGPT.":"Permintaan ChatGPT gagal. Periksa internet, izin akun dan model.";goto done;}
 CgResponseError response_error;answer=cg_completed_ex(response,&response_error);if(!answer){*error=cg_response_error(response_error);goto done;}q=cg_quote(answer);if(q){size_t rn=strlen(q)+100;result=malloc(rn);if(result)snprintf(result,rn,"{\"choices\":[{\"message\":{\"content\":%s}}]}",q);free(q);}if(!result)*error="Jawaban ChatGPT tidak dapat diproses.";
 done:cg_clear(access);free(model);cg_clear(response);cg_clear(input);cg_clear(body);cg_clear(answer);return result;
}
static DWORD WINAPI cg_worker(void *context){
 CgJob *job=context;Reply *reply=calloc(1,sizeof(*reply));const char *error=NULL;char *data=NULL;BOOL welcome=FALSE,remote=TRUE;CgStore s={0};HANDLE m=NULL;
 if(!reply)goto done;reply->id=job->id;
 if(!strcmp(job->op,"chatgptAI")){data=cg_ai(job,&error);goto deliver;}
 m=cg_mutex();if(!m||!cg_load(&s)){error="Akun ChatGPT tidak dapat dibaca. Data lama tidak diganti.";goto deliver;}CgAccount *a=cg_active(&s);
 if(!strcmp(job->op,"chatgptLogin")){error=cg_login(&s,job->payload,&welcome);}
 else if(!strcmp(job->op,"chatgptSwitch")){BOOL found=FALSE;for(int i=0;i<s.count;i++)if(!strcmp(s.accounts[i].client,job->payload))found=TRUE;if(!found)error="Akun ChatGPT tidak ditemukan.";else{free(s.active);s.active=_strdup(job->payload);if(!s.active||!cg_save(&s))error="Akun belum dapat dipilih.";}}
 else if(!strcmp(job->op,"chatgptModels")){error=cg_renew(&s,a);if(!error&&!cg_scope(a->scope,"chatgpt.tokens.use.direct"))error="Akun belum memberi izin penggunaan paket ChatGPT.";if(!error)error=cg_models(a);if(!error&&!cg_save(&s))error="Model belum dapat disimpan.";}
 else if(!strcmp(job->op,"chatgptChoose")){CgJson j=cg_json(job->payload);char *g=j.t?cg_get(&j,0,"general"):NULL,*c=j.t?cg_get(&j,0,"coding"):NULL;if(!a||!g||!c||!cg_model_allowed(a,g)||!cg_model_allowed(a,c))error="Pilih model yang tersedia untuk akun ini.";else{free(a->general);free(a->coding);a->general=g;a->coding=c;g=c=NULL;if(!cg_save(&s))error="Pilihan model belum tersimpan.";}free(g);free(c);free(j.t);}
 else if(!strcmp(job->op,"chatgptSignOut")){if(a){remote=cg_revoke(a);cg_clear(a->access);cg_clear(a->refresh);cg_clear(a->identity);a->access=_strdup("");a->refresh=_strdup("");a->identity=_strdup("");a->expiry=0;if(!cg_save(&s))error="Sesi lokal belum dapat dihapus.";}}
 else if(!strcmp(job->op,"chatgptWelcome")){if(a){a->welcomed=TRUE;if(!cg_save(&s))error="Pengaturan belum tersimpan.";}}
 else if(!strcmp(job->op,"aiProvider")){if(strcmp(job->payload,"chatgpt")&&strcmp(job->payload,"openrouter"))error="Penyedia AI tidak valid.";else if(!write_local(L"ai.provider",job->payload,(DWORD)strlen(job->payload),FALSE))error="Pilihan penyedia AI belum tersimpan.";}
 else if(strcmp(job->op,"chatgptStatus"))error="Operasi ChatGPT tidak dikenal.";
 if(!error){char *status=cg_status(&s);if(status){size_t n=strlen(status)+100;data=malloc(n);if(data){status[strlen(status)-1]=0;snprintf(data,n,"%s,\"welcome\":%s,\"remoteRevoked\":%s}",status,welcome?"true":"false",remote?"true":"false");}free(status);}}
 deliver:cg_free_store(&s);cg_unlock(m);reply->ok=!error&&data;reply->data=data;if(!reply->ok){free(data);char *q=cg_quote(error?error:"Operasi ChatGPT gagal.");if(q){size_t n=strlen(q)+30;reply->data=malloc(n);if(reply->data)snprintf(reply->data,n,"{\"error\":%s}",q);free(q);}}
 done:if(strcmp(job->op,"chatgptAI"))InterlockedExchange(&cg_control,0);release_ai_slot();if(reply&&(!reply->data||!PostMessageW(job->window,BRIDGE_REPLY,0,(LPARAM)reply))){free(reply->data);free(reply);}cg_clear(job->payload);free(job->op);free(job);return 0;
}
static BOOL cg_start(App *app,unsigned long id,const char *op,const WCHAR *payload,BOOL coding){
 BOOL ai=!strcmp(op,"chatgptAI");if(ai&&InterlockedCompareExchange(&cg_control,0,0)){fail_reply(app,id,"Koneksi ChatGPT sedang diatur. Tunggu sebentar.");return FALSE;}if(!ai&&InterlockedCompareExchange(&cg_control,1,0)){fail_reply(app,id,"Operasi ChatGPT sedang berjalan.");return FALSE;}
 if(!ai&&strcmp(op,"chatgptStatus")&&InterlockedCompareExchange(&ai_pending,0,0)){InterlockedExchange(&cg_control,0);fail_reply(app,id,"Tunggu tugas AI selesai sebelum mengubah koneksi.");return FALSE;}
 if(!reserve_ai_slot()){if(!ai)InterlockedExchange(&cg_control,0);fail_reply(app,id,"Tiga permintaan AI sedang berjalan. Tunggu sebentar.");return FALSE;}
 CgJob *job=calloc(1,sizeof(*job));HANDLE thread=NULL;if(job){job->window=app->window;job->id=id;job->coding=coding;job->op=_strdup(op);job->payload=to_utf8(payload);if(job->op&&job->payload&&strlen(job->payload)<500000)thread=CreateThread(NULL,0,cg_worker,job,0,NULL);}
 if(thread){CloseHandle(thread);return TRUE;}if(job){free(job->op);cg_clear(job->payload);free(job);}if(!ai)InterlockedExchange(&cg_control,0);release_ai_slot();fail_reply(app,id,"Operasi ChatGPT tidak dapat dimulai.");return FALSE;
}
static BOOL cg_operation(App *app,const WCHAR *op,unsigned long id,const WCHAR *payload){
 if(!wcscmp(op,L"chatgptCancel")){InterlockedExchange(&cg_cancel,1);send_reply(app,id,TRUE,"true");return TRUE;}
 if(!wcscmp(op,L"chatgptUsage")){BOOL ok=(INT_PTR)ShellExecuteW(app->window,L"open",CG_USAGE,NULL,NULL,SW_SHOWNORMAL)>32;if(ok)send_reply(app,id,TRUE,"true");else fail_reply(app,id,"Browser tidak dapat dibuka.");return TRUE;}
 if(!wcscmp(op,L"aiProvider")||!wcsncmp(op,L"chatgpt",7)){char *operation=to_utf8(op);if(operation){if(!strcmp(operation,"chatgptLogin"))InterlockedExchange(&cg_cancel,0);cg_start(app,id,operation,payload,FALSE);free(operation);}else fail_reply(app,id,"Operasi tidak valid.");return TRUE;}return FALSE;
}
