/* Outbound-only HTTPS relay. Device token is DPAPI encrypted and never returned to JS. */
static volatile LONG sync_busy=0;
typedef struct SyncJob {HWND window;unsigned long id;char *payload;BOOL pair;} SyncJob;
static char *sync_load(void){DWORD n=0;char *bytes=read_local(L"phone-sync.dpapi",10000,&n,NULL);if(!bytes)return NULL;DATA_BLOB in={n,(BYTE*)bytes},out={0};BOOL ok=CryptUnprotectData(&in,NULL,NULL,NULL,NULL,CRYPTPROTECT_UI_FORBIDDEN,&out);free(bytes);if(!ok)return NULL;char *text=calloc((size_t)out.cbData+1,1);if(text)memcpy(text,out.pbData,out.cbData);SecureZeroMemory(out.pbData,out.cbData);LocalFree(out.pbData);return text;}
static BOOL sync_save(const char *text){DATA_BLOB in={(DWORD)strlen(text),(BYTE*)text},out={0};if(!CryptProtectData(&in,L"DITASHA phone pairing",NULL,NULL,NULL,CRYPTPROTECT_UI_FORBIDDEN,&out))return FALSE;BOOL ok=write_local(L"phone-sync.dpapi",out.pbData,out.cbData,FALSE);SecureZeroMemory(out.pbData,out.cbData);LocalFree(out.pbData);return ok;}
static DWORD WINAPI sync_worker(void *context){
 SyncJob *job=context;Reply *reply=calloc(1,sizeof(*reply));char *saved=NULL,*base=NULL,*key=NULL,*body=NULL,*path=NULL,*response=NULL;WCHAR *url=NULL;CgJson input=cg_json(job->payload),config={0};DWORD status=0;const char *error="Sync belum berhasil. Periksa HTTPS server dan koneksi internet.";
 if(!reply)goto done;reply->id=job->id;if(!input.t)goto done;
 if(job->pair){base=cg_get(&input,0,"url");char *code=cg_get(&input,0,"code"),*name=cg_get(&input,0,"name");BOOL valid=code&&strlen(code)==8&&name&&*name&&strlen(name)<=240;if(code)for(char *p=code;*p;p++)if(*p<'0'||*p>'9')valid=FALSE;
  if(valid){char *qc=cg_quote(code),*qn=cg_quote(name);size_t n=qc&&qn?strlen(qc)+strlen(qn)+64:0;body=n?malloc(n):NULL;if(body)snprintf(body,n,"{\"code\":%s,\"name\":%s}",qc,qn);free(qc);free(qn);}free(code);free(name);key=_strdup("");path=_strdup("/api/pc/pair");if(!valid){error="Kode pairing harus 8 digit, dan nama PC wajib diisi.";goto done;}
 }else{
  saved=sync_load();config=cg_json(saved);if(!config.t){error="Pasangkan PC lewat Pengaturan → Sync ponsel dahulu.";goto done;}base=cg_get(&config,0,"url");key=cg_get(&config,0,"token");path=cg_get(&input,0,"path");body=cg_raw(&input,cg_field(&input,0,"body"));
  if(!path||(strcmp(path,"/api/pc/claim")&&strcmp(path,"/api/pc/heartbeat")&&strcmp(path,"/api/pc/snapshot")&&strcmp(path,"/api/pc/complete")&&strcmp(path,"/api/pc/recover")&&strcmp(path,"/api/pc/reconcile"))||!body||!json_root(body,JSMN_OBJECT)){error="Operasi sync tidak valid.";goto done;}
 }
 if(!base||!key||!body||!path)goto done;WCHAR *suffix=to_wide(path);if(!suffix)goto done;BOOL valid=api_url(4,base,suffix,&url);free(suffix);if(!valid){error="Gunakan alamat HTTPS server tanpa path, query, atau password.";goto done;}
 response=api_http(url,body,key,&status);if(status==401){error=job->pair?"Kode pairing salah, kedaluwarsa, atau sudah dipakai.":"Akses PC dicabut. Pasangkan ulang melalui ponsel.";goto done;}if(status==409){error="Tugas tidak lagi aktif di server. Tinjau antrean ponsel.";goto done;}if(status<200||status>=300||!response||!json_root(response,JSMN_OBJECT))goto done;
 if(job->pair){CgJson result=cg_json(response);char *token=cg_get(&result,0,"token"),*device=cg_get(&result,0,"id");if(token&&strlen(token)==64&&strspn(token,"0123456789abcdef")==64&&device&&strlen(device)==36&&strspn(device,"0123456789abcdef-")==36){char *qb=cg_quote(base),*qt=cg_quote(token),*qd=cg_quote(device);size_t n=qb&&qt&&qd?strlen(qb)+strlen(qt)+strlen(qd)+80:0;char *record=n?malloc(n):NULL;if(record){snprintf(record,n,"{\"url\":%s,\"token\":%s,\"deviceId\":%s}",qb,qt,qd);if(sync_save(record)){reply->ok=TRUE;reply->data=_strdup("{\"paired\":true}");}cg_clear(record);}free(qb);free(qt);free(qd);}cg_clear(token);free(device);free(result.t);if(!reply->ok){error="Pairing diterima server tetapi belum tersimpan. Buat kode baru dan coba lagi.";goto done;}}
 else{reply->ok=TRUE;reply->data=response;response=NULL;}
done:
 if(reply){if(!reply->ok){char *quoted=cg_quote(error);size_t n=quoted?strlen(quoted)+32:0;reply->data=n?malloc(n):NULL;if(reply->data)snprintf(reply->data,n,"{\"error\":%s}",quoted);free(quoted);}if(!reply->data||!PostMessageW(job->window,BRIDGE_REPLY,0,(LPARAM)reply)){free(reply->data);free(reply);}}
 cg_clear(saved);free(base);cg_clear(key);cg_clear(body);free(path);cg_clear(response);free(url);free(input.t);free(config.t);cg_clear(job->payload);free(job);InterlockedExchange(&sync_busy,0);return 0;
}
static BOOL sync_operation(App *app,const WCHAR *op,unsigned long id,const WCHAR *payload){
 if(!wcscmp(op,L"syncStatus")){char *saved=sync_load();CgJson j=cg_json(saved);char *url=j.t?cg_get(&j,0,"url"):NULL,*device=j.t?cg_get(&j,0,"deviceId"):NULL,*token=j.t?cg_get(&j,0,"token"):NULL;if(url&&device&&token){char *qu=cg_quote(url),*qd=cg_quote(device);size_t n=qu&&qd?strlen(qu)+strlen(qd)+80:0;char *result=n?malloc(n):NULL;if(result){snprintf(result,n,"{\"paired\":true,\"url\":%s,\"deviceId\":%s}",qu,qd);send_reply(app,id,TRUE,result);free(result);}else fail_reply(app,id,"Status sync tidak dapat dibaca.");free(qu);free(qd);}else send_reply(app,id,TRUE,"{\"paired\":false}");free(url);free(device);cg_clear(token);free(j.t);cg_clear(saved);return TRUE;}
 if(!wcscmp(op,L"syncDisconnect")){if(InterlockedCompareExchange(&sync_busy,0,0)){fail_reply(app,id,"Tunggu sync selesai sebelum melepas PC.");return TRUE;}WCHAR path[MAX_PATH];local_path(L"phone-sync.dpapi",path);if(DeleteFileW(path)||GetLastError()==ERROR_FILE_NOT_FOUND)send_reply(app,id,TRUE,"{\"paired\":false}");else fail_reply(app,id,"Pairing lokal belum dapat dihapus.");return TRUE;}
 if(wcscmp(op,L"syncPair")&&wcscmp(op,L"syncRequest"))return FALSE;if(InterlockedCompareExchange(&sync_busy,1,0)){fail_reply(app,id,"Sync sebelumnya belum selesai.");return TRUE;}
 SyncJob *job=calloc(1,sizeof(*job));HANDLE thread=NULL;if(job){job->window=app->window;job->id=id;job->pair=!wcscmp(op,L"syncPair");job->payload=to_utf8(payload);if(job->payload&&strlen(job->payload)<8000000&&json_root(job->payload,JSMN_OBJECT))thread=CreateThread(NULL,0,sync_worker,job,0,NULL);}if(thread)CloseHandle(thread);else{if(job){cg_clear(job->payload);free(job);}InterlockedExchange(&sync_busy,0);fail_reply(app,id,"Permintaan sync tidak dapat dimulai.");}return TRUE;
}
